-- Convert dollar amount columns from String to Decimal
-- NOTE: Run during a maintenance window; MODIFY COLUMN will rewrite parts as needed.

-- Drop dependent view + materialized view so column type changes can proceed cleanly.
DROP VIEW IF EXISTS kalshi_signals.vw_market_snapshots_latest;
DROP TABLE IF EXISTS kalshi_signals.mv_market_snapshots_latest;

-- Base table: market_snapshots
ALTER TABLE kalshi_signals.market_snapshots
    MODIFY COLUMN SettlementValueDollars Nullable(Decimal(18, 4)),
    MODIFY COLUMN YesBidDollars Decimal(18, 4),
    MODIFY COLUMN YesAskDollars Decimal(18, 4),
    MODIFY COLUMN NoBidDollars Decimal(18, 4),
    MODIFY COLUMN NoAskDollars Decimal(18, 4),
    MODIFY COLUMN LastPriceDollars Decimal(18, 4),
    MODIFY COLUMN PreviousYesBidDollars Decimal(18, 4),
    MODIFY COLUMN PreviousYesAskDollars Decimal(18, 4),
    MODIFY COLUMN PreviousPriceDollars Decimal(18, 4),
    MODIFY COLUMN NotionalValueDollars Decimal(18, 4),
    MODIFY COLUMN LiquidityDollars Decimal(18, 4);

-- Latest table: market_snapshots_latest
ALTER TABLE kalshi_signals.market_snapshots_latest
    MODIFY COLUMN SettlementValueDollars Nullable(Decimal(18, 4)),
    MODIFY COLUMN YesBidDollars Decimal(18, 4),
    MODIFY COLUMN YesAskDollars Decimal(18, 4),
    MODIFY COLUMN NoBidDollars Decimal(18, 4),
    MODIFY COLUMN NoAskDollars Decimal(18, 4),
    MODIFY COLUMN LastPriceDollars Decimal(18, 4),
    MODIFY COLUMN PreviousYesBidDollars Decimal(18, 4),
    MODIFY COLUMN PreviousYesAskDollars Decimal(18, 4),
    MODIFY COLUMN PreviousPriceDollars Decimal(18, 4),
    MODIFY COLUMN NotionalValueDollars Decimal(18, 4),
    MODIFY COLUMN LiquidityDollars Decimal(18, 4);

-- Recreate materialized view with updated types
CREATE MATERIALIZED VIEW kalshi_signals.mv_market_snapshots_latest TO kalshi_signals.market_snapshots_latest
(
    `MarketSnapshotID` UUID,
    `Ticker` String,
    `EventTicker` String,
    `MarketType` String,
    `YesSubTitle` String,
    `NoSubTitle` String,
    `CreatedTime` DateTime,
    `OpenTime` DateTime,
    `CloseTime` DateTime,
    `ExpectedExpirationTime` Nullable(DateTime),
    `LatestExpirationTime` DateTime,
    `FeeWaiverExpirationTime` Nullable(DateTime),
    `SettlementValue` Nullable(Int32),
    `SettlementValueDollars` Nullable(Decimal(18, 4)),
    `Status` String,
    `Result` String,
    `CanCloseEarly` UInt8,
    `ResponsePriceUnits` String,
    `YesBid` Decimal(18, 8),
    `YesBidDollars` Decimal(18, 4),
    `YesAsk` Decimal(18, 8),
    `YesAskDollars` Decimal(18, 4),
    `NoBid` Decimal(18, 8),
    `NoBidDollars` Decimal(18, 4),
    `NoAsk` Decimal(18, 8),
    `NoAskDollars` Decimal(18, 4),
    `LastPrice` Decimal(18, 8),
    `LastPriceDollars` Decimal(18, 4),
    `PreviousYesBid` Int32,
    `PreviousYesBidDollars` Decimal(18, 4),
    `PreviousYesAsk` Int32,
    `PreviousYesAskDollars` Decimal(18, 4),
    `PreviousPrice` Int32,
    `PreviousPriceDollars` Decimal(18, 4),
    `Volume` Int32,
    `Volume24h` Int32,
    `OpenInterest` Int32,
    `NotionalValue` Int32,
    `NotionalValueDollars` Decimal(18, 4),
    `Liquidity` Int32,
    `LiquidityDollars` Decimal(18, 4),
    `ExpirationValue` String,
    `TickSize` Int32,
    `StrikeType` Nullable(String),
    `FloorStrike` Nullable(Float64),
    `CapStrike` Nullable(Float64),
    `FunctionalStrike` Nullable(String),
    `CustomStrike` Nullable(String),
    `MveCollectionTicker` Nullable(String),
    `MveSelectedLegs` Nullable(String),
    `PrimaryParticipantKey` Nullable(String),
    `PriceLevelStructure` String,
    `PriceRanges` Nullable(String),
    `GenerateDate` DateTime
)
AS SELECT
    MarketSnapshotID,
    Ticker,
    EventTicker,
    MarketType,
    YesSubTitle,
    NoSubTitle,
    CreatedTime,
    OpenTime,
    CloseTime,
    ExpectedExpirationTime,
    LatestExpirationTime,
    FeeWaiverExpirationTime,
    SettlementValue,
    SettlementValueDollars,
    Status,
    Result,
    CanCloseEarly,
    ResponsePriceUnits,
    YesBid,
    YesBidDollars,
    YesAsk,
    YesAskDollars,
    NoBid,
    NoBidDollars,
    NoAsk,
    NoAskDollars,
    LastPrice,
    LastPriceDollars,
    PreviousYesBid,
    PreviousYesBidDollars,
    PreviousYesAsk,
    PreviousYesAskDollars,
    PreviousPrice,
    PreviousPriceDollars,
    Volume,
    Volume24h,
    OpenInterest,
    NotionalValue,
    NotionalValueDollars,
    Liquidity,
    LiquidityDollars,
    ExpirationValue,
    TickSize,
    StrikeType,
    FloorStrike,
    CapStrike,
    FunctionalStrike,
    CustomStrike,
    MveCollectionTicker,
    MveSelectedLegs,
    PrimaryParticipantKey,
    PriceLevelStructure,
    PriceRanges,
    GenerateDate
FROM kalshi_signals.market_snapshots;

-- Recreate view used by EF Core
CREATE VIEW kalshi_signals.vw_market_snapshots_latest
(
    `MarketSnapshotID` UUID,
    `Ticker` String,
    `EventTicker` String,
    `MarketType` String,
    `YesSubTitle` String,
    `NoSubTitle` String,
    `CreatedTime` DateTime,
    `OpenTime` DateTime,
    `CloseTime` DateTime,
    `ExpectedExpirationTime` Nullable(DateTime),
    `LatestExpirationTime` DateTime,
    `FeeWaiverExpirationTime` Nullable(DateTime),
    `SettlementValue` Nullable(Int32),
    `SettlementValueDollars` Nullable(Decimal(18, 4)),
    `Status` String,
    `Result` String,
    `CanCloseEarly` UInt8,
    `ResponsePriceUnits` String,
    `YesBid` Decimal(18, 8),
    `YesBidDollars` Decimal(18, 4),
    `YesAsk` Decimal(18, 8),
    `YesAskDollars` Decimal(18, 4),
    `NoBid` Decimal(18, 8),
    `NoBidDollars` Decimal(18, 4),
    `NoAsk` Decimal(18, 8),
    `NoAskDollars` Decimal(18, 4),
    `LastPrice` Decimal(18, 8),
    `LastPriceDollars` Decimal(18, 4),
    `PreviousYesBid` Int32,
    `PreviousYesBidDollars` Decimal(18, 4),
    `PreviousYesAsk` Int32,
    `PreviousYesAskDollars` Decimal(18, 4),
    `PreviousPrice` Int32,
    `PreviousPriceDollars` Decimal(18, 4),
    `Volume` Int32,
    `Volume24h` Int32,
    `OpenInterest` Int32,
    `NotionalValue` Int32,
    `NotionalValueDollars` Decimal(18, 4),
    `Liquidity` Int32,
    `LiquidityDollars` Decimal(18, 4),
    `ExpirationValue` String,
    `TickSize` Int32,
    `StrikeType` Nullable(String),
    `FloorStrike` Nullable(Float64),
    `CapStrike` Nullable(Float64),
    `FunctionalStrike` Nullable(String),
    `CustomStrike` Nullable(String),
    `MveCollectionTicker` Nullable(String),
    `MveSelectedLegs` Nullable(String),
    `PrimaryParticipantKey` Nullable(String),
    `PriceLevelStructure` String,
    `PriceRanges` Nullable(String),
    `GenerateDate` DateTime
)
AS SELECT *
FROM kalshi_signals.market_snapshots_latest
FINAL;
