// <auto-generated />
using System;
using KSignal.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSignal.API.Migrations
{
    [DbContext(typeof(KalshiDbContext))]
    partial class KalshiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KSignal.API.Models.MarketCache", b =>
                {
                    b.Property<string>("TickerId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JsonResponse")
                        .HasColumnType("longtext");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LastPriceDollars")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LatestExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Liquidity")
                        .HasColumnType("int");

                    b.Property<string>("LiquidityDollars")
                        .HasColumnType("longtext");

                    b.Property<decimal>("NoAsk")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NoAskDollars")
                        .HasColumnType("longtext");

                    b.Property<decimal>("NoBid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NoBidDollars")
                        .HasColumnType("longtext");

                    b.Property<int>("NotionalValue")
                        .HasColumnType("int");

                    b.Property<string>("NotionalValueDollars")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PreviousPrice")
                        .HasColumnType("int");

                    b.Property<string>("PreviousPriceDollars")
                        .HasColumnType("longtext");

                    b.Property<int>("PreviousYesAsk")
                        .HasColumnType("int");

                    b.Property<string>("PreviousYesAskDollars")
                        .HasColumnType("longtext");

                    b.Property<int>("PreviousYesBid")
                        .HasColumnType("int");

                    b.Property<string>("PreviousYesBidDollars")
                        .HasColumnType("longtext");

                    b.Property<string>("SeriesTicker")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SettlementValue")
                        .HasColumnType("int");

                    b.Property<string>("SettlementValueDollars")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Subtitle")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.Property<int>("Volume24h")
                        .HasColumnType("int");

                    b.Property<decimal>("YesAsk")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("YesAskDollars")
                        .HasColumnType("longtext");

                    b.Property<decimal>("YesBid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("YesBidDollars")
                        .HasColumnType("longtext");

                    b.HasKey("TickerId");

                    b.HasIndex("SeriesTicker");

                    b.ToTable("Markets", (string)null);
                });

            modelBuilder.Entity("KSignal.API.Models.MarketCategory", b =>
                {
                    b.Property<string>("SeriesId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Frequency")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("JsonResponse")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Ticker")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("SeriesId");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("idx_series_id");

                    b.ToTable("MarketCategories", (string)null);
                });

            modelBuilder.Entity("KSignal.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirebaseId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsComnEmailOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
