// <auto-generated />
using System;
using KSignal.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSignal.API.Migrations
{
    [DbContext(typeof(KalshiDbContext))]
    partial class KalshiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KSignal.API.Models.MarketSnapshot", b =>
                {
                    b.Property<int>("MarketSnapshotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CanCloseEarly")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("CapStrike")
                        .HasColumnType("double");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomStrike")
                        .HasColumnType("longtext");

                    b.Property<string>("EarlyCloseCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("EventTicker")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ExpectedExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExpirationValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FeeWaiverExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("FloorStrike")
                        .HasColumnType("double");

                    b.Property<string>("FunctionalStrike")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("GenerateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LastPriceDollars")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LatestExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Liquidity")
                        .HasColumnType("int");

                    b.Property<string>("LiquidityDollars")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MveCollectionTicker")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MveSelectedLegs")
                        .HasColumnType("longtext");

                    b.Property<decimal>("NoAsk")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NoAskDollars")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("NoBid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NoBidDollars")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoSubTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NotionalValue")
                        .HasColumnType("int");

                    b.Property<string>("NotionalValueDollars")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OpenInterest")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PreviousPrice")
                        .HasColumnType("int");

                    b.Property<string>("PreviousPriceDollars")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PreviousYesAsk")
                        .HasColumnType("int");

                    b.Property<string>("PreviousYesAskDollars")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PreviousYesBid")
                        .HasColumnType("int");

                    b.Property<string>("PreviousYesBidDollars")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PriceLevelStructure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PriceRanges")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryParticipantKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResponsePriceUnits")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RulesPrimary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RulesSecondary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SettlementTimerSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("SettlementValue")
                        .HasColumnType("int");

                    b.Property<string>("SettlementValueDollars")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("StrikeType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TickSize")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.Property<int>("Volume24h")
                        .HasColumnType("int");

                    b.Property<decimal>("YesAsk")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("YesAskDollars")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("YesBid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("YesBidDollars")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YesSubTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MarketSnapshotID");

                    b.HasIndex("EventTicker");

                    b.HasIndex("Ticker");

                    b.ToTable("market_snapshots", (string)null);
                });

            modelBuilder.Entity("KSignal.API.Models.TagsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Tag")
                        .IsUnique();

                    b.ToTable("TagsCategories", (string)null);
                });

            modelBuilder.Entity("KSignal.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirebaseId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsComnEmailOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
