/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Kalshi.Api.Client;
using Kalshi.Api.Model;

namespace Kalshi.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IApiKeysApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for creating a new API key with a user-provided public key.  This endpoint allows users with Premier or Market Maker API usage levels to create API keys by providing their own RSA public key. The platform will use this public key to verify signatures on API requests.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CreateApiKeyResponse</returns>
        CreateApiKeyResponse CreateApiKey(CreateApiKeyRequest createApiKeyRequest, int operationIndex = 0);

        /// <summary>
        /// Create API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for creating a new API key with a user-provided public key.  This endpoint allows users with Premier or Market Maker API usage levels to create API keys by providing their own RSA public key. The platform will use this public key to verify signatures on API requests.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CreateApiKeyResponse</returns>
        ApiResponse<CreateApiKeyResponse> CreateApiKeyWithHttpInfo(CreateApiKeyRequest createApiKeyRequest, int operationIndex = 0);
        /// <summary>
        /// Delete API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for deleting an existing API key.  This endpoint permanently deletes an API key. Once deleted, the key can no longer be used for authentication. This action cannot be undone.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">API key ID to delete</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void DeleteApiKey(string apiKey, int operationIndex = 0);

        /// <summary>
        /// Delete API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for deleting an existing API key.  This endpoint permanently deletes an API key. Once deleted, the key can no longer be used for authentication. This action cannot be undone.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">API key ID to delete</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteApiKeyWithHttpInfo(string apiKey, int operationIndex = 0);
        /// <summary>
        /// Generate API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for generating a new API key with an automatically created key pair.  This endpoint generates both a public and private RSA key pair. The public key is stored on the platform, while the private key is returned to the user and must be stored securely. The private key cannot be retrieved again.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GenerateApiKeyResponse</returns>
        GenerateApiKeyResponse GenerateApiKey(GenerateApiKeyRequest generateApiKeyRequest, int operationIndex = 0);

        /// <summary>
        /// Generate API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for generating a new API key with an automatically created key pair.  This endpoint generates both a public and private RSA key pair. The public key is stored on the platform, while the private key is returned to the user and must be stored securely. The private key cannot be retrieved again.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GenerateApiKeyResponse</returns>
        ApiResponse<GenerateApiKeyResponse> GenerateApiKeyWithHttpInfo(GenerateApiKeyRequest generateApiKeyRequest, int operationIndex = 0);
        /// <summary>
        /// Get API Keys
        /// </summary>
        /// <remarks>
        ///  Endpoint for retrieving all API keys associated with the authenticated user.  API keys allow programmatic access to the platform without requiring username/password authentication. Each key has a unique identifier and name.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetApiKeysResponse</returns>
        GetApiKeysResponse GetApiKeys(int operationIndex = 0);

        /// <summary>
        /// Get API Keys
        /// </summary>
        /// <remarks>
        ///  Endpoint for retrieving all API keys associated with the authenticated user.  API keys allow programmatic access to the platform without requiring username/password authentication. Each key has a unique identifier and name.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetApiKeysResponse</returns>
        ApiResponse<GetApiKeysResponse> GetApiKeysWithHttpInfo(int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IApiKeysApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for creating a new API key with a user-provided public key.  This endpoint allows users with Premier or Market Maker API usage levels to create API keys by providing their own RSA public key. The platform will use this public key to verify signatures on API requests.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateApiKeyResponse</returns>
        System.Threading.Tasks.Task<CreateApiKeyResponse> CreateApiKeyAsync(CreateApiKeyRequest createApiKeyRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for creating a new API key with a user-provided public key.  This endpoint allows users with Premier or Market Maker API usage levels to create API keys by providing their own RSA public key. The platform will use this public key to verify signatures on API requests.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateApiKeyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateApiKeyResponse>> CreateApiKeyWithHttpInfoAsync(CreateApiKeyRequest createApiKeyRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for deleting an existing API key.  This endpoint permanently deletes an API key. Once deleted, the key can no longer be used for authentication. This action cannot be undone.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">API key ID to delete</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteApiKeyAsync(string apiKey, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for deleting an existing API key.  This endpoint permanently deletes an API key. Once deleted, the key can no longer be used for authentication. This action cannot be undone.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">API key ID to delete</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteApiKeyWithHttpInfoAsync(string apiKey, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Generate API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for generating a new API key with an automatically created key pair.  This endpoint generates both a public and private RSA key pair. The public key is stored on the platform, while the private key is returned to the user and must be stored securely. The private key cannot be retrieved again.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GenerateApiKeyResponse</returns>
        System.Threading.Tasks.Task<GenerateApiKeyResponse> GenerateApiKeyAsync(GenerateApiKeyRequest generateApiKeyRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Generate API Key
        /// </summary>
        /// <remarks>
        ///  Endpoint for generating a new API key with an automatically created key pair.  This endpoint generates both a public and private RSA key pair. The public key is stored on the platform, while the private key is returned to the user and must be stored securely. The private key cannot be retrieved again.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GenerateApiKeyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GenerateApiKeyResponse>> GenerateApiKeyWithHttpInfoAsync(GenerateApiKeyRequest generateApiKeyRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get API Keys
        /// </summary>
        /// <remarks>
        ///  Endpoint for retrieving all API keys associated with the authenticated user.  API keys allow programmatic access to the platform without requiring username/password authentication. Each key has a unique identifier and name.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetApiKeysResponse</returns>
        System.Threading.Tasks.Task<GetApiKeysResponse> GetApiKeysAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get API Keys
        /// </summary>
        /// <remarks>
        ///  Endpoint for retrieving all API keys associated with the authenticated user.  API keys allow programmatic access to the platform without requiring username/password authentication. Each key has a unique identifier and name.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetApiKeysResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetApiKeysResponse>> GetApiKeysWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IApiKeysApi : IApiKeysApiSync, IApiKeysApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ApiKeysApi : IApiKeysApi
    {
        private Kalshi.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeysApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ApiKeysApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeysApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ApiKeysApi(string basePath)
        {
            this.Configuration = Kalshi.Api.Client.Configuration.MergeConfigurations(
                Kalshi.Api.Client.GlobalConfiguration.Instance,
                new Kalshi.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeysApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ApiKeysApi(Kalshi.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Kalshi.Api.Client.Configuration.MergeConfigurations(
                Kalshi.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeysApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ApiKeysApi(Kalshi.Api.Client.ISynchronousClient client, Kalshi.Api.Client.IAsynchronousClient asyncClient, Kalshi.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Kalshi.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Kalshi.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Kalshi.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Kalshi.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create API Key  Endpoint for creating a new API key with a user-provided public key.  This endpoint allows users with Premier or Market Maker API usage levels to create API keys by providing their own RSA public key. The platform will use this public key to verify signatures on API requests.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CreateApiKeyResponse</returns>
        public CreateApiKeyResponse CreateApiKey(CreateApiKeyRequest createApiKeyRequest, int operationIndex = 0)
        {
            Kalshi.Api.Client.ApiResponse<CreateApiKeyResponse> localVarResponse = CreateApiKeyWithHttpInfo(createApiKeyRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create API Key  Endpoint for creating a new API key with a user-provided public key.  This endpoint allows users with Premier or Market Maker API usage levels to create API keys by providing their own RSA public key. The platform will use this public key to verify signatures on API requests.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CreateApiKeyResponse</returns>
        public Kalshi.Api.Client.ApiResponse<CreateApiKeyResponse> CreateApiKeyWithHttpInfo(CreateApiKeyRequest createApiKeyRequest, int operationIndex = 0)
        {
            // verify the required parameter 'createApiKeyRequest' is set
            if (createApiKeyRequest == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'createApiKeyRequest' when calling ApiKeysApi->CreateApiKey");
            }

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createApiKeyRequest;

            localVarRequestOptions.Operation = "ApiKeysApi.CreateApiKey";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateApiKeyResponse>("/api_keys", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateApiKey", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create API Key  Endpoint for creating a new API key with a user-provided public key.  This endpoint allows users with Premier or Market Maker API usage levels to create API keys by providing their own RSA public key. The platform will use this public key to verify signatures on API requests.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateApiKeyResponse</returns>
        public async System.Threading.Tasks.Task<CreateApiKeyResponse> CreateApiKeyAsync(CreateApiKeyRequest createApiKeyRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Kalshi.Api.Client.ApiResponse<CreateApiKeyResponse> localVarResponse = await CreateApiKeyWithHttpInfoAsync(createApiKeyRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create API Key  Endpoint for creating a new API key with a user-provided public key.  This endpoint allows users with Premier or Market Maker API usage levels to create API keys by providing their own RSA public key. The platform will use this public key to verify signatures on API requests.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateApiKeyResponse)</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<CreateApiKeyResponse>> CreateApiKeyWithHttpInfoAsync(CreateApiKeyRequest createApiKeyRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createApiKeyRequest' is set
            if (createApiKeyRequest == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'createApiKeyRequest' when calling ApiKeysApi->CreateApiKey");
            }


            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createApiKeyRequest;

            localVarRequestOptions.Operation = "ApiKeysApi.CreateApiKey";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateApiKeyResponse>("/api_keys", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateApiKey", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete API Key  Endpoint for deleting an existing API key.  This endpoint permanently deletes an API key. Once deleted, the key can no longer be used for authentication. This action cannot be undone.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">API key ID to delete</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void DeleteApiKey(string apiKey, int operationIndex = 0)
        {
            DeleteApiKeyWithHttpInfo(apiKey);
        }

        /// <summary>
        /// Delete API Key  Endpoint for deleting an existing API key.  This endpoint permanently deletes an API key. Once deleted, the key can no longer be used for authentication. This action cannot be undone.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">API key ID to delete</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Kalshi.Api.Client.ApiResponse<Object> DeleteApiKeyWithHttpInfo(string apiKey, int operationIndex = 0)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'apiKey' when calling ApiKeysApi->DeleteApiKey");
            }

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("api_key", Kalshi.Api.Client.ClientUtils.ParameterToString(apiKey)); // path parameter

            localVarRequestOptions.Operation = "ApiKeysApi.DeleteApiKey";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api_keys/{api_key}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteApiKey", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete API Key  Endpoint for deleting an existing API key.  This endpoint permanently deletes an API key. Once deleted, the key can no longer be used for authentication. This action cannot be undone.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">API key ID to delete</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteApiKeyAsync(string apiKey, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            await DeleteApiKeyWithHttpInfoAsync(apiKey, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete API Key  Endpoint for deleting an existing API key.  This endpoint permanently deletes an API key. Once deleted, the key can no longer be used for authentication. This action cannot be undone.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiKey">API key ID to delete</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<Object>> DeleteApiKeyWithHttpInfoAsync(string apiKey, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'apiKey' is set
            if (apiKey == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'apiKey' when calling ApiKeysApi->DeleteApiKey");
            }


            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("api_key", Kalshi.Api.Client.ClientUtils.ParameterToString(apiKey)); // path parameter

            localVarRequestOptions.Operation = "ApiKeysApi.DeleteApiKey";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api_keys/{api_key}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteApiKey", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Generate API Key  Endpoint for generating a new API key with an automatically created key pair.  This endpoint generates both a public and private RSA key pair. The public key is stored on the platform, while the private key is returned to the user and must be stored securely. The private key cannot be retrieved again.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GenerateApiKeyResponse</returns>
        public GenerateApiKeyResponse GenerateApiKey(GenerateApiKeyRequest generateApiKeyRequest, int operationIndex = 0)
        {
            Kalshi.Api.Client.ApiResponse<GenerateApiKeyResponse> localVarResponse = GenerateApiKeyWithHttpInfo(generateApiKeyRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Generate API Key  Endpoint for generating a new API key with an automatically created key pair.  This endpoint generates both a public and private RSA key pair. The public key is stored on the platform, while the private key is returned to the user and must be stored securely. The private key cannot be retrieved again.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GenerateApiKeyResponse</returns>
        public Kalshi.Api.Client.ApiResponse<GenerateApiKeyResponse> GenerateApiKeyWithHttpInfo(GenerateApiKeyRequest generateApiKeyRequest, int operationIndex = 0)
        {
            // verify the required parameter 'generateApiKeyRequest' is set
            if (generateApiKeyRequest == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'generateApiKeyRequest' when calling ApiKeysApi->GenerateApiKey");
            }

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = generateApiKeyRequest;

            localVarRequestOptions.Operation = "ApiKeysApi.GenerateApiKey";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = this.Client.Post<GenerateApiKeyResponse>("/api_keys/generate", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GenerateApiKey", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Generate API Key  Endpoint for generating a new API key with an automatically created key pair.  This endpoint generates both a public and private RSA key pair. The public key is stored on the platform, while the private key is returned to the user and must be stored securely. The private key cannot be retrieved again.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GenerateApiKeyResponse</returns>
        public async System.Threading.Tasks.Task<GenerateApiKeyResponse> GenerateApiKeyAsync(GenerateApiKeyRequest generateApiKeyRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Kalshi.Api.Client.ApiResponse<GenerateApiKeyResponse> localVarResponse = await GenerateApiKeyWithHttpInfoAsync(generateApiKeyRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Generate API Key  Endpoint for generating a new API key with an automatically created key pair.  This endpoint generates both a public and private RSA key pair. The public key is stored on the platform, while the private key is returned to the user and must be stored securely. The private key cannot be retrieved again.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateApiKeyRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GenerateApiKeyResponse)</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<GenerateApiKeyResponse>> GenerateApiKeyWithHttpInfoAsync(GenerateApiKeyRequest generateApiKeyRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'generateApiKeyRequest' is set
            if (generateApiKeyRequest == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'generateApiKeyRequest' when calling ApiKeysApi->GenerateApiKey");
            }


            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = generateApiKeyRequest;

            localVarRequestOptions.Operation = "ApiKeysApi.GenerateApiKey";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<GenerateApiKeyResponse>("/api_keys/generate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GenerateApiKey", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get API Keys  Endpoint for retrieving all API keys associated with the authenticated user.  API keys allow programmatic access to the platform without requiring username/password authentication. Each key has a unique identifier and name.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetApiKeysResponse</returns>
        public GetApiKeysResponse GetApiKeys(int operationIndex = 0)
        {
            Kalshi.Api.Client.ApiResponse<GetApiKeysResponse> localVarResponse = GetApiKeysWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get API Keys  Endpoint for retrieving all API keys associated with the authenticated user.  API keys allow programmatic access to the platform without requiring username/password authentication. Each key has a unique identifier and name.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetApiKeysResponse</returns>
        public Kalshi.Api.Client.ApiResponse<GetApiKeysResponse> GetApiKeysWithHttpInfo(int operationIndex = 0)
        {
            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ApiKeysApi.GetApiKeys";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetApiKeysResponse>("/api_keys", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetApiKeys", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get API Keys  Endpoint for retrieving all API keys associated with the authenticated user.  API keys allow programmatic access to the platform without requiring username/password authentication. Each key has a unique identifier and name.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetApiKeysResponse</returns>
        public async System.Threading.Tasks.Task<GetApiKeysResponse> GetApiKeysAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Kalshi.Api.Client.ApiResponse<GetApiKeysResponse> localVarResponse = await GetApiKeysWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get API Keys  Endpoint for retrieving all API keys associated with the authenticated user.  API keys allow programmatic access to the platform without requiring username/password authentication. Each key has a unique identifier and name.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetApiKeysResponse)</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<GetApiKeysResponse>> GetApiKeysWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ApiKeysApi.GetApiKeys";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetApiKeysResponse>("/api_keys", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetApiKeys", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
