/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Kalshi.Api.Client;
using Kalshi.Api.Model;

namespace Kalshi.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFcmApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get FCM Orders
        /// </summary>
        /// <remarks>
        /// Endpoint for FCM members to get orders filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering orders by subtrader ID. 
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to orders for a specific subtrader (FCM members only)</param>
        /// <param name="cursor">Pagination cursor. Use the cursor value returned from the previous response to get the next page of results. Leave empty for the first page. (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions. Multiple event tickers can be provided as a comma-separated list (maximum 10). (optional)</param>
        /// <param name="ticker">Filter by market ticker (optional)</param>
        /// <param name="minTs">Restricts the response to orders after a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="maxTs">Restricts the response to orders before a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="status">Restricts the response to orders that have a certain status (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetOrdersResponse</returns>
        GetOrdersResponse GetFCMOrders(string subtraderId, string? cursor = default, string? eventTicker = default, string? ticker = default, long? minTs = default, long? maxTs = default, string? status = default, int? limit = default, int operationIndex = 0);

        /// <summary>
        /// Get FCM Orders
        /// </summary>
        /// <remarks>
        /// Endpoint for FCM members to get orders filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering orders by subtrader ID. 
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to orders for a specific subtrader (FCM members only)</param>
        /// <param name="cursor">Pagination cursor. Use the cursor value returned from the previous response to get the next page of results. Leave empty for the first page. (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions. Multiple event tickers can be provided as a comma-separated list (maximum 10). (optional)</param>
        /// <param name="ticker">Filter by market ticker (optional)</param>
        /// <param name="minTs">Restricts the response to orders after a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="maxTs">Restricts the response to orders before a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="status">Restricts the response to orders that have a certain status (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetOrdersResponse</returns>
        ApiResponse<GetOrdersResponse> GetFCMOrdersWithHttpInfo(string subtraderId, string? cursor = default, string? eventTicker = default, string? ticker = default, long? minTs = default, long? maxTs = default, string? status = default, int? limit = default, int operationIndex = 0);
        /// <summary>
        /// Get FCM Positions
        /// </summary>
        /// <remarks>
        /// Endpoint for FCM members to get market positions filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering positions by subtrader ID. 
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to positions for a specific subtrader (FCM members only)</param>
        /// <param name="ticker">Ticker of desired positions (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions (optional)</param>
        /// <param name="countFilter">Restricts the positions to those with any of following fields with non-zero values, as a comma separated list (optional)</param>
        /// <param name="settlementStatus">Settlement status of the markets to return. Defaults to unsettled (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="cursor">The Cursor represents a pointer to the next page of records in the pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetPositionsResponse</returns>
        GetPositionsResponse GetFCMPositions(string subtraderId, string? ticker = default, string? eventTicker = default, string? countFilter = default, string? settlementStatus = default, int? limit = default, string? cursor = default, int operationIndex = 0);

        /// <summary>
        /// Get FCM Positions
        /// </summary>
        /// <remarks>
        /// Endpoint for FCM members to get market positions filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering positions by subtrader ID. 
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to positions for a specific subtrader (FCM members only)</param>
        /// <param name="ticker">Ticker of desired positions (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions (optional)</param>
        /// <param name="countFilter">Restricts the positions to those with any of following fields with non-zero values, as a comma separated list (optional)</param>
        /// <param name="settlementStatus">Settlement status of the markets to return. Defaults to unsettled (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="cursor">The Cursor represents a pointer to the next page of records in the pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetPositionsResponse</returns>
        ApiResponse<GetPositionsResponse> GetFCMPositionsWithHttpInfo(string subtraderId, string? ticker = default, string? eventTicker = default, string? countFilter = default, string? settlementStatus = default, int? limit = default, string? cursor = default, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFcmApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get FCM Orders
        /// </summary>
        /// <remarks>
        /// Endpoint for FCM members to get orders filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering orders by subtrader ID. 
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to orders for a specific subtrader (FCM members only)</param>
        /// <param name="cursor">Pagination cursor. Use the cursor value returned from the previous response to get the next page of results. Leave empty for the first page. (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions. Multiple event tickers can be provided as a comma-separated list (maximum 10). (optional)</param>
        /// <param name="ticker">Filter by market ticker (optional)</param>
        /// <param name="minTs">Restricts the response to orders after a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="maxTs">Restricts the response to orders before a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="status">Restricts the response to orders that have a certain status (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetOrdersResponse</returns>
        System.Threading.Tasks.Task<GetOrdersResponse> GetFCMOrdersAsync(string subtraderId, string? cursor = default, string? eventTicker = default, string? ticker = default, long? minTs = default, long? maxTs = default, string? status = default, int? limit = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get FCM Orders
        /// </summary>
        /// <remarks>
        /// Endpoint for FCM members to get orders filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering orders by subtrader ID. 
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to orders for a specific subtrader (FCM members only)</param>
        /// <param name="cursor">Pagination cursor. Use the cursor value returned from the previous response to get the next page of results. Leave empty for the first page. (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions. Multiple event tickers can be provided as a comma-separated list (maximum 10). (optional)</param>
        /// <param name="ticker">Filter by market ticker (optional)</param>
        /// <param name="minTs">Restricts the response to orders after a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="maxTs">Restricts the response to orders before a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="status">Restricts the response to orders that have a certain status (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetOrdersResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetOrdersResponse>> GetFCMOrdersWithHttpInfoAsync(string subtraderId, string? cursor = default, string? eventTicker = default, string? ticker = default, long? minTs = default, long? maxTs = default, string? status = default, int? limit = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get FCM Positions
        /// </summary>
        /// <remarks>
        /// Endpoint for FCM members to get market positions filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering positions by subtrader ID. 
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to positions for a specific subtrader (FCM members only)</param>
        /// <param name="ticker">Ticker of desired positions (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions (optional)</param>
        /// <param name="countFilter">Restricts the positions to those with any of following fields with non-zero values, as a comma separated list (optional)</param>
        /// <param name="settlementStatus">Settlement status of the markets to return. Defaults to unsettled (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="cursor">The Cursor represents a pointer to the next page of records in the pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPositionsResponse</returns>
        System.Threading.Tasks.Task<GetPositionsResponse> GetFCMPositionsAsync(string subtraderId, string? ticker = default, string? eventTicker = default, string? countFilter = default, string? settlementStatus = default, int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get FCM Positions
        /// </summary>
        /// <remarks>
        /// Endpoint for FCM members to get market positions filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering positions by subtrader ID. 
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to positions for a specific subtrader (FCM members only)</param>
        /// <param name="ticker">Ticker of desired positions (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions (optional)</param>
        /// <param name="countFilter">Restricts the positions to those with any of following fields with non-zero values, as a comma separated list (optional)</param>
        /// <param name="settlementStatus">Settlement status of the markets to return. Defaults to unsettled (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="cursor">The Cursor represents a pointer to the next page of records in the pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPositionsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetPositionsResponse>> GetFCMPositionsWithHttpInfoAsync(string subtraderId, string? ticker = default, string? eventTicker = default, string? countFilter = default, string? settlementStatus = default, int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFcmApi : IFcmApiSync, IFcmApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FcmApi : IFcmApi
    {
        private Kalshi.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FcmApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FcmApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FcmApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FcmApi(string basePath)
        {
            this.Configuration = Kalshi.Api.Client.Configuration.MergeConfigurations(
                Kalshi.Api.Client.GlobalConfiguration.Instance,
                new Kalshi.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FcmApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FcmApi(Kalshi.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Kalshi.Api.Client.Configuration.MergeConfigurations(
                Kalshi.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FcmApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public FcmApi(Kalshi.Api.Client.ISynchronousClient client, Kalshi.Api.Client.IAsynchronousClient asyncClient, Kalshi.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Kalshi.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Kalshi.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Kalshi.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Kalshi.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get FCM Orders Endpoint for FCM members to get orders filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering orders by subtrader ID. 
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to orders for a specific subtrader (FCM members only)</param>
        /// <param name="cursor">Pagination cursor. Use the cursor value returned from the previous response to get the next page of results. Leave empty for the first page. (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions. Multiple event tickers can be provided as a comma-separated list (maximum 10). (optional)</param>
        /// <param name="ticker">Filter by market ticker (optional)</param>
        /// <param name="minTs">Restricts the response to orders after a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="maxTs">Restricts the response to orders before a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="status">Restricts the response to orders that have a certain status (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetOrdersResponse</returns>
        public GetOrdersResponse GetFCMOrders(string subtraderId, string? cursor = default, string? eventTicker = default, string? ticker = default, long? minTs = default, long? maxTs = default, string? status = default, int? limit = default, int operationIndex = 0)
        {
            Kalshi.Api.Client.ApiResponse<GetOrdersResponse> localVarResponse = GetFCMOrdersWithHttpInfo(subtraderId, cursor, eventTicker, ticker, minTs, maxTs, status, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get FCM Orders Endpoint for FCM members to get orders filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering orders by subtrader ID. 
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to orders for a specific subtrader (FCM members only)</param>
        /// <param name="cursor">Pagination cursor. Use the cursor value returned from the previous response to get the next page of results. Leave empty for the first page. (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions. Multiple event tickers can be provided as a comma-separated list (maximum 10). (optional)</param>
        /// <param name="ticker">Filter by market ticker (optional)</param>
        /// <param name="minTs">Restricts the response to orders after a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="maxTs">Restricts the response to orders before a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="status">Restricts the response to orders that have a certain status (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetOrdersResponse</returns>
        public Kalshi.Api.Client.ApiResponse<GetOrdersResponse> GetFCMOrdersWithHttpInfo(string subtraderId, string? cursor = default, string? eventTicker = default, string? ticker = default, long? minTs = default, long? maxTs = default, string? status = default, int? limit = default, int operationIndex = 0)
        {
            // verify the required parameter 'subtraderId' is set
            if (subtraderId == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'subtraderId' when calling FcmApi->GetFCMOrders");
            }

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "subtrader_id", subtraderId));
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (eventTicker != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "event_ticker", eventTicker));
            }
            if (ticker != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "ticker", ticker));
            }
            if (minTs != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "min_ts", minTs));
            }
            if (maxTs != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "max_ts", maxTs));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            localVarRequestOptions.Operation = "FcmApi.GetFCMOrders";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetOrdersResponse>("/fcm/orders", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFCMOrders", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get FCM Orders Endpoint for FCM members to get orders filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering orders by subtrader ID. 
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to orders for a specific subtrader (FCM members only)</param>
        /// <param name="cursor">Pagination cursor. Use the cursor value returned from the previous response to get the next page of results. Leave empty for the first page. (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions. Multiple event tickers can be provided as a comma-separated list (maximum 10). (optional)</param>
        /// <param name="ticker">Filter by market ticker (optional)</param>
        /// <param name="minTs">Restricts the response to orders after a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="maxTs">Restricts the response to orders before a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="status">Restricts the response to orders that have a certain status (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetOrdersResponse</returns>
        public async System.Threading.Tasks.Task<GetOrdersResponse> GetFCMOrdersAsync(string subtraderId, string? cursor = default, string? eventTicker = default, string? ticker = default, long? minTs = default, long? maxTs = default, string? status = default, int? limit = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Kalshi.Api.Client.ApiResponse<GetOrdersResponse> localVarResponse = await GetFCMOrdersWithHttpInfoAsync(subtraderId, cursor, eventTicker, ticker, minTs, maxTs, status, limit, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get FCM Orders Endpoint for FCM members to get orders filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering orders by subtrader ID. 
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to orders for a specific subtrader (FCM members only)</param>
        /// <param name="cursor">Pagination cursor. Use the cursor value returned from the previous response to get the next page of results. Leave empty for the first page. (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions. Multiple event tickers can be provided as a comma-separated list (maximum 10). (optional)</param>
        /// <param name="ticker">Filter by market ticker (optional)</param>
        /// <param name="minTs">Restricts the response to orders after a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="maxTs">Restricts the response to orders before a timestamp, formatted as a Unix Timestamp (optional)</param>
        /// <param name="status">Restricts the response to orders that have a certain status (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetOrdersResponse)</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<GetOrdersResponse>> GetFCMOrdersWithHttpInfoAsync(string subtraderId, string? cursor = default, string? eventTicker = default, string? ticker = default, long? minTs = default, long? maxTs = default, string? status = default, int? limit = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'subtraderId' is set
            if (subtraderId == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'subtraderId' when calling FcmApi->GetFCMOrders");
            }


            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "subtrader_id", subtraderId));
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (eventTicker != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "event_ticker", eventTicker));
            }
            if (ticker != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "ticker", ticker));
            }
            if (minTs != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "min_ts", minTs));
            }
            if (maxTs != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "max_ts", maxTs));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            localVarRequestOptions.Operation = "FcmApi.GetFCMOrders";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetOrdersResponse>("/fcm/orders", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFCMOrders", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get FCM Positions Endpoint for FCM members to get market positions filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering positions by subtrader ID. 
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to positions for a specific subtrader (FCM members only)</param>
        /// <param name="ticker">Ticker of desired positions (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions (optional)</param>
        /// <param name="countFilter">Restricts the positions to those with any of following fields with non-zero values, as a comma separated list (optional)</param>
        /// <param name="settlementStatus">Settlement status of the markets to return. Defaults to unsettled (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="cursor">The Cursor represents a pointer to the next page of records in the pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetPositionsResponse</returns>
        public GetPositionsResponse GetFCMPositions(string subtraderId, string? ticker = default, string? eventTicker = default, string? countFilter = default, string? settlementStatus = default, int? limit = default, string? cursor = default, int operationIndex = 0)
        {
            Kalshi.Api.Client.ApiResponse<GetPositionsResponse> localVarResponse = GetFCMPositionsWithHttpInfo(subtraderId, ticker, eventTicker, countFilter, settlementStatus, limit, cursor);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get FCM Positions Endpoint for FCM members to get market positions filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering positions by subtrader ID. 
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to positions for a specific subtrader (FCM members only)</param>
        /// <param name="ticker">Ticker of desired positions (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions (optional)</param>
        /// <param name="countFilter">Restricts the positions to those with any of following fields with non-zero values, as a comma separated list (optional)</param>
        /// <param name="settlementStatus">Settlement status of the markets to return. Defaults to unsettled (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="cursor">The Cursor represents a pointer to the next page of records in the pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetPositionsResponse</returns>
        public Kalshi.Api.Client.ApiResponse<GetPositionsResponse> GetFCMPositionsWithHttpInfo(string subtraderId, string? ticker = default, string? eventTicker = default, string? countFilter = default, string? settlementStatus = default, int? limit = default, string? cursor = default, int operationIndex = 0)
        {
            // verify the required parameter 'subtraderId' is set
            if (subtraderId == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'subtraderId' when calling FcmApi->GetFCMPositions");
            }

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "subtrader_id", subtraderId));
            if (ticker != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "ticker", ticker));
            }
            if (eventTicker != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "event_ticker", eventTicker));
            }
            if (countFilter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "count_filter", countFilter));
            }
            if (settlementStatus != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "settlement_status", settlementStatus));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "FcmApi.GetFCMPositions";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetPositionsResponse>("/fcm/positions", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFCMPositions", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get FCM Positions Endpoint for FCM members to get market positions filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering positions by subtrader ID. 
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to positions for a specific subtrader (FCM members only)</param>
        /// <param name="ticker">Ticker of desired positions (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions (optional)</param>
        /// <param name="countFilter">Restricts the positions to those with any of following fields with non-zero values, as a comma separated list (optional)</param>
        /// <param name="settlementStatus">Settlement status of the markets to return. Defaults to unsettled (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="cursor">The Cursor represents a pointer to the next page of records in the pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPositionsResponse</returns>
        public async System.Threading.Tasks.Task<GetPositionsResponse> GetFCMPositionsAsync(string subtraderId, string? ticker = default, string? eventTicker = default, string? countFilter = default, string? settlementStatus = default, int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Kalshi.Api.Client.ApiResponse<GetPositionsResponse> localVarResponse = await GetFCMPositionsWithHttpInfoAsync(subtraderId, ticker, eventTicker, countFilter, settlementStatus, limit, cursor, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get FCM Positions Endpoint for FCM members to get market positions filtered by subtrader ID. This endpoint requires FCM member access level and allows filtering positions by subtrader ID. 
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="subtraderId">Restricts the response to positions for a specific subtrader (FCM members only)</param>
        /// <param name="ticker">Ticker of desired positions (optional)</param>
        /// <param name="eventTicker">Event ticker of desired positions (optional)</param>
        /// <param name="countFilter">Restricts the positions to those with any of following fields with non-zero values, as a comma separated list (optional)</param>
        /// <param name="settlementStatus">Settlement status of the markets to return. Defaults to unsettled (optional)</param>
        /// <param name="limit">Parameter to specify the number of results per page. Defaults to 100 (optional)</param>
        /// <param name="cursor">The Cursor represents a pointer to the next page of records in the pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPositionsResponse)</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<GetPositionsResponse>> GetFCMPositionsWithHttpInfoAsync(string subtraderId, string? ticker = default, string? eventTicker = default, string? countFilter = default, string? settlementStatus = default, int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'subtraderId' is set
            if (subtraderId == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'subtraderId' when calling FcmApi->GetFCMPositions");
            }


            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "subtrader_id", subtraderId));
            if (ticker != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "ticker", ticker));
            }
            if (eventTicker != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "event_ticker", eventTicker));
            }
            if (countFilter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "count_filter", countFilter));
            }
            if (settlementStatus != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "settlement_status", settlementStatus));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "FcmApi.GetFCMPositions";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (kalshiAccessSignature, kalshiAccessKey, kalshiAccessTimestamp) required
            AuthenticationHelper.AddAuthenticationHeaders(localVarRequestOptions, this.Configuration);

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetPositionsResponse>("/fcm/positions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetFCMPositions", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
