/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Kalshi.Api.Client;
using Kalshi.Api.Model;

namespace Kalshi.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIncentiveProgramsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Volume Incentives
        /// </summary>
        /// <remarks>
        ///  List volume incentives with optional filters. Volume incentives are rewards programs for trading activity on specific markets.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">Status filter. Can be \&quot;all\&quot;, \&quot;active\&quot;, \&quot;upcoming\&quot;, \&quot;closed\&quot;, or \&quot;paid_out\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="type">Type filter. Can be \&quot;all\&quot;, \&quot;liquidity\&quot;, or \&quot;volume\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="limit">Number of results per page. Defaults to 100. Maximum value is 10000. (optional)</param>
        /// <param name="cursor">Cursor for pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetIncentiveProgramsResponse</returns>
        GetIncentiveProgramsResponse GetIncentivePrograms(string? status = default, string? type = default, int? limit = default, string? cursor = default, int operationIndex = 0);

        /// <summary>
        /// Get Volume Incentives
        /// </summary>
        /// <remarks>
        ///  List volume incentives with optional filters. Volume incentives are rewards programs for trading activity on specific markets.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">Status filter. Can be \&quot;all\&quot;, \&quot;active\&quot;, \&quot;upcoming\&quot;, \&quot;closed\&quot;, or \&quot;paid_out\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="type">Type filter. Can be \&quot;all\&quot;, \&quot;liquidity\&quot;, or \&quot;volume\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="limit">Number of results per page. Defaults to 100. Maximum value is 10000. (optional)</param>
        /// <param name="cursor">Cursor for pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetIncentiveProgramsResponse</returns>
        ApiResponse<GetIncentiveProgramsResponse> GetIncentiveProgramsWithHttpInfo(string? status = default, string? type = default, int? limit = default, string? cursor = default, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIncentiveProgramsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Volume Incentives
        /// </summary>
        /// <remarks>
        ///  List volume incentives with optional filters. Volume incentives are rewards programs for trading activity on specific markets.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">Status filter. Can be \&quot;all\&quot;, \&quot;active\&quot;, \&quot;upcoming\&quot;, \&quot;closed\&quot;, or \&quot;paid_out\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="type">Type filter. Can be \&quot;all\&quot;, \&quot;liquidity\&quot;, or \&quot;volume\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="limit">Number of results per page. Defaults to 100. Maximum value is 10000. (optional)</param>
        /// <param name="cursor">Cursor for pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetIncentiveProgramsResponse</returns>
        System.Threading.Tasks.Task<GetIncentiveProgramsResponse> GetIncentiveProgramsAsync(string? status = default, string? type = default, int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Volume Incentives
        /// </summary>
        /// <remarks>
        ///  List volume incentives with optional filters. Volume incentives are rewards programs for trading activity on specific markets.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">Status filter. Can be \&quot;all\&quot;, \&quot;active\&quot;, \&quot;upcoming\&quot;, \&quot;closed\&quot;, or \&quot;paid_out\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="type">Type filter. Can be \&quot;all\&quot;, \&quot;liquidity\&quot;, or \&quot;volume\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="limit">Number of results per page. Defaults to 100. Maximum value is 10000. (optional)</param>
        /// <param name="cursor">Cursor for pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetIncentiveProgramsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetIncentiveProgramsResponse>> GetIncentiveProgramsWithHttpInfoAsync(string? status = default, string? type = default, int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIncentiveProgramsApi : IIncentiveProgramsApiSync, IIncentiveProgramsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class IncentiveProgramsApi : IIncentiveProgramsApi
    {
        private Kalshi.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="IncentiveProgramsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public IncentiveProgramsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IncentiveProgramsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public IncentiveProgramsApi(string basePath)
        {
            this.Configuration = Kalshi.Api.Client.Configuration.MergeConfigurations(
                Kalshi.Api.Client.GlobalConfiguration.Instance,
                new Kalshi.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IncentiveProgramsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public IncentiveProgramsApi(Kalshi.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Kalshi.Api.Client.Configuration.MergeConfigurations(
                Kalshi.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IncentiveProgramsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public IncentiveProgramsApi(Kalshi.Api.Client.ISynchronousClient client, Kalshi.Api.Client.IAsynchronousClient asyncClient, Kalshi.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Kalshi.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Kalshi.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Kalshi.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Kalshi.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Volume Incentives  List volume incentives with optional filters. Volume incentives are rewards programs for trading activity on specific markets.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">Status filter. Can be \&quot;all\&quot;, \&quot;active\&quot;, \&quot;upcoming\&quot;, \&quot;closed\&quot;, or \&quot;paid_out\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="type">Type filter. Can be \&quot;all\&quot;, \&quot;liquidity\&quot;, or \&quot;volume\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="limit">Number of results per page. Defaults to 100. Maximum value is 10000. (optional)</param>
        /// <param name="cursor">Cursor for pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetIncentiveProgramsResponse</returns>
        public GetIncentiveProgramsResponse GetIncentivePrograms(string? status = default, string? type = default, int? limit = default, string? cursor = default, int operationIndex = 0)
        {
            Kalshi.Api.Client.ApiResponse<GetIncentiveProgramsResponse> localVarResponse = GetIncentiveProgramsWithHttpInfo(status, type, limit, cursor);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Volume Incentives  List volume incentives with optional filters. Volume incentives are rewards programs for trading activity on specific markets.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">Status filter. Can be \&quot;all\&quot;, \&quot;active\&quot;, \&quot;upcoming\&quot;, \&quot;closed\&quot;, or \&quot;paid_out\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="type">Type filter. Can be \&quot;all\&quot;, \&quot;liquidity\&quot;, or \&quot;volume\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="limit">Number of results per page. Defaults to 100. Maximum value is 10000. (optional)</param>
        /// <param name="cursor">Cursor for pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetIncentiveProgramsResponse</returns>
        public Kalshi.Api.Client.ApiResponse<GetIncentiveProgramsResponse> GetIncentiveProgramsWithHttpInfo(string? status = default, string? type = default, int? limit = default, string? cursor = default, int operationIndex = 0)
        {
            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "IncentiveProgramsApi.GetIncentivePrograms";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<GetIncentiveProgramsResponse>("/incentive_programs", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetIncentivePrograms", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Volume Incentives  List volume incentives with optional filters. Volume incentives are rewards programs for trading activity on specific markets.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">Status filter. Can be \&quot;all\&quot;, \&quot;active\&quot;, \&quot;upcoming\&quot;, \&quot;closed\&quot;, or \&quot;paid_out\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="type">Type filter. Can be \&quot;all\&quot;, \&quot;liquidity\&quot;, or \&quot;volume\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="limit">Number of results per page. Defaults to 100. Maximum value is 10000. (optional)</param>
        /// <param name="cursor">Cursor for pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetIncentiveProgramsResponse</returns>
        public async System.Threading.Tasks.Task<GetIncentiveProgramsResponse> GetIncentiveProgramsAsync(string? status = default, string? type = default, int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Kalshi.Api.Client.ApiResponse<GetIncentiveProgramsResponse> localVarResponse = await GetIncentiveProgramsWithHttpInfoAsync(status, type, limit, cursor, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Volume Incentives  List volume incentives with optional filters. Volume incentives are rewards programs for trading activity on specific markets.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status">Status filter. Can be \&quot;all\&quot;, \&quot;active\&quot;, \&quot;upcoming\&quot;, \&quot;closed\&quot;, or \&quot;paid_out\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="type">Type filter. Can be \&quot;all\&quot;, \&quot;liquidity\&quot;, or \&quot;volume\&quot;. Default is \&quot;all\&quot;. (optional)</param>
        /// <param name="limit">Number of results per page. Defaults to 100. Maximum value is 10000. (optional)</param>
        /// <param name="cursor">Cursor for pagination (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetIncentiveProgramsResponse)</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<GetIncentiveProgramsResponse>> GetIncentiveProgramsWithHttpInfoAsync(string? status = default, string? type = default, int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "IncentiveProgramsApi.GetIncentivePrograms";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetIncentiveProgramsResponse>("/incentive_programs", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetIncentivePrograms", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
