/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Kalshi.Api.Client;
using Kalshi.Api.Model;

namespace Kalshi.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILiveDataApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Live Data
        /// </summary>
        /// <remarks>
        /// Get live data for a specific milestone
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Type of live data</param>
        /// <param name="milestoneId">Milestone ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetLiveDataResponse</returns>
        GetLiveDataResponse GetLiveData(string type, string milestoneId, int operationIndex = 0);

        /// <summary>
        /// Get Live Data
        /// </summary>
        /// <remarks>
        /// Get live data for a specific milestone
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Type of live data</param>
        /// <param name="milestoneId">Milestone ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetLiveDataResponse</returns>
        ApiResponse<GetLiveDataResponse> GetLiveDataWithHttpInfo(string type, string milestoneId, int operationIndex = 0);
        /// <summary>
        /// Get Multiple Live Data
        /// </summary>
        /// <remarks>
        /// Get live data for multiple milestones
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="milestoneIds">Array of milestone IDs</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetLiveDatasResponse</returns>
        GetLiveDatasResponse GetLiveDatas(List<string> milestoneIds, int operationIndex = 0);

        /// <summary>
        /// Get Multiple Live Data
        /// </summary>
        /// <remarks>
        /// Get live data for multiple milestones
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="milestoneIds">Array of milestone IDs</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetLiveDatasResponse</returns>
        ApiResponse<GetLiveDatasResponse> GetLiveDatasWithHttpInfo(List<string> milestoneIds, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILiveDataApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Live Data
        /// </summary>
        /// <remarks>
        /// Get live data for a specific milestone
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Type of live data</param>
        /// <param name="milestoneId">Milestone ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetLiveDataResponse</returns>
        System.Threading.Tasks.Task<GetLiveDataResponse> GetLiveDataAsync(string type, string milestoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Live Data
        /// </summary>
        /// <remarks>
        /// Get live data for a specific milestone
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Type of live data</param>
        /// <param name="milestoneId">Milestone ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetLiveDataResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetLiveDataResponse>> GetLiveDataWithHttpInfoAsync(string type, string milestoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Multiple Live Data
        /// </summary>
        /// <remarks>
        /// Get live data for multiple milestones
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="milestoneIds">Array of milestone IDs</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetLiveDatasResponse</returns>
        System.Threading.Tasks.Task<GetLiveDatasResponse> GetLiveDatasAsync(List<string> milestoneIds, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Multiple Live Data
        /// </summary>
        /// <remarks>
        /// Get live data for multiple milestones
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="milestoneIds">Array of milestone IDs</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetLiveDatasResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetLiveDatasResponse>> GetLiveDatasWithHttpInfoAsync(List<string> milestoneIds, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILiveDataApi : ILiveDataApiSync, ILiveDataApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LiveDataApi : ILiveDataApi
    {
        private Kalshi.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LiveDataApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LiveDataApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LiveDataApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LiveDataApi(string basePath)
        {
            this.Configuration = Kalshi.Api.Client.Configuration.MergeConfigurations(
                Kalshi.Api.Client.GlobalConfiguration.Instance,
                new Kalshi.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LiveDataApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LiveDataApi(Kalshi.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Kalshi.Api.Client.Configuration.MergeConfigurations(
                Kalshi.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LiveDataApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public LiveDataApi(Kalshi.Api.Client.ISynchronousClient client, Kalshi.Api.Client.IAsynchronousClient asyncClient, Kalshi.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Kalshi.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Kalshi.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Kalshi.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Kalshi.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Live Data Get live data for a specific milestone
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Type of live data</param>
        /// <param name="milestoneId">Milestone ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetLiveDataResponse</returns>
        public GetLiveDataResponse GetLiveData(string type, string milestoneId, int operationIndex = 0)
        {
            Kalshi.Api.Client.ApiResponse<GetLiveDataResponse> localVarResponse = GetLiveDataWithHttpInfo(type, milestoneId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Live Data Get live data for a specific milestone
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Type of live data</param>
        /// <param name="milestoneId">Milestone ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetLiveDataResponse</returns>
        public Kalshi.Api.Client.ApiResponse<GetLiveDataResponse> GetLiveDataWithHttpInfo(string type, string milestoneId, int operationIndex = 0)
        {
            // verify the required parameter 'type' is set
            if (type == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'type' when calling LiveDataApi->GetLiveData");
            }

            // verify the required parameter 'milestoneId' is set
            if (milestoneId == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'milestoneId' when calling LiveDataApi->GetLiveData");
            }

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("type", Kalshi.Api.Client.ClientUtils.ParameterToString(type)); // path parameter
            localVarRequestOptions.PathParameters.Add("milestone_id", Kalshi.Api.Client.ClientUtils.ParameterToString(milestoneId)); // path parameter

            localVarRequestOptions.Operation = "LiveDataApi.GetLiveData";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<GetLiveDataResponse>("/live_data/{type}/milestone/{milestone_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLiveData", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Live Data Get live data for a specific milestone
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Type of live data</param>
        /// <param name="milestoneId">Milestone ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetLiveDataResponse</returns>
        public async System.Threading.Tasks.Task<GetLiveDataResponse> GetLiveDataAsync(string type, string milestoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Kalshi.Api.Client.ApiResponse<GetLiveDataResponse> localVarResponse = await GetLiveDataWithHttpInfoAsync(type, milestoneId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Live Data Get live data for a specific milestone
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Type of live data</param>
        /// <param name="milestoneId">Milestone ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetLiveDataResponse)</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<GetLiveDataResponse>> GetLiveDataWithHttpInfoAsync(string type, string milestoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'type' is set
            if (type == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'type' when calling LiveDataApi->GetLiveData");
            }

            // verify the required parameter 'milestoneId' is set
            if (milestoneId == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'milestoneId' when calling LiveDataApi->GetLiveData");
            }


            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("type", Kalshi.Api.Client.ClientUtils.ParameterToString(type)); // path parameter
            localVarRequestOptions.PathParameters.Add("milestone_id", Kalshi.Api.Client.ClientUtils.ParameterToString(milestoneId)); // path parameter

            localVarRequestOptions.Operation = "LiveDataApi.GetLiveData";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetLiveDataResponse>("/live_data/{type}/milestone/{milestone_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLiveData", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Multiple Live Data Get live data for multiple milestones
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="milestoneIds">Array of milestone IDs</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetLiveDatasResponse</returns>
        public GetLiveDatasResponse GetLiveDatas(List<string> milestoneIds, int operationIndex = 0)
        {
            Kalshi.Api.Client.ApiResponse<GetLiveDatasResponse> localVarResponse = GetLiveDatasWithHttpInfo(milestoneIds);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Multiple Live Data Get live data for multiple milestones
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="milestoneIds">Array of milestone IDs</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetLiveDatasResponse</returns>
        public Kalshi.Api.Client.ApiResponse<GetLiveDatasResponse> GetLiveDatasWithHttpInfo(List<string> milestoneIds, int operationIndex = 0)
        {
            // verify the required parameter 'milestoneIds' is set
            if (milestoneIds == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'milestoneIds' when calling LiveDataApi->GetLiveDatas");
            }

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("multi", "milestone_ids", milestoneIds));

            localVarRequestOptions.Operation = "LiveDataApi.GetLiveDatas";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<GetLiveDatasResponse>("/live_data/batch", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLiveDatas", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Multiple Live Data Get live data for multiple milestones
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="milestoneIds">Array of milestone IDs</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetLiveDatasResponse</returns>
        public async System.Threading.Tasks.Task<GetLiveDatasResponse> GetLiveDatasAsync(List<string> milestoneIds, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Kalshi.Api.Client.ApiResponse<GetLiveDatasResponse> localVarResponse = await GetLiveDatasWithHttpInfoAsync(milestoneIds, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Multiple Live Data Get live data for multiple milestones
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="milestoneIds">Array of milestone IDs</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetLiveDatasResponse)</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<GetLiveDatasResponse>> GetLiveDatasWithHttpInfoAsync(List<string> milestoneIds, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'milestoneIds' is set
            if (milestoneIds == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'milestoneIds' when calling LiveDataApi->GetLiveDatas");
            }


            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("multi", "milestone_ids", milestoneIds));

            localVarRequestOptions.Operation = "LiveDataApi.GetLiveDatas";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetLiveDatasResponse>("/live_data/batch", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLiveDatas", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
