/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Kalshi.Api.Client;
using Kalshi.Api.Model;

namespace Kalshi.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStructuredTargetsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Structured Target
        /// </summary>
        /// <remarks>
        ///  Endpoint for getting data about a specific structured target by its ID.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="structuredTargetId">Structured target ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStructuredTargetResponse</returns>
        GetStructuredTargetResponse GetStructuredTarget(string structuredTargetId, int operationIndex = 0);

        /// <summary>
        /// Get Structured Target
        /// </summary>
        /// <remarks>
        ///  Endpoint for getting data about a specific structured target by its ID.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="structuredTargetId">Structured target ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStructuredTargetResponse</returns>
        ApiResponse<GetStructuredTargetResponse> GetStructuredTargetWithHttpInfo(string structuredTargetId, int operationIndex = 0);
        /// <summary>
        /// Get Structured Targets
        /// </summary>
        /// <remarks>
        /// Page size (min: 1, max: 2000)
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Filter by structured target type (optional)</param>
        /// <param name="competition">Filter by competition (optional)</param>
        /// <param name="pageSize">Number of items per page (min 1, max 2000, default 100) (optional, default to 100)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStructuredTargetsResponse</returns>
        GetStructuredTargetsResponse GetStructuredTargets(string? type = default, string? competition = default, int? pageSize = default, string? cursor = default, int operationIndex = 0);

        /// <summary>
        /// Get Structured Targets
        /// </summary>
        /// <remarks>
        /// Page size (min: 1, max: 2000)
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Filter by structured target type (optional)</param>
        /// <param name="competition">Filter by competition (optional)</param>
        /// <param name="pageSize">Number of items per page (min 1, max 2000, default 100) (optional, default to 100)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStructuredTargetsResponse</returns>
        ApiResponse<GetStructuredTargetsResponse> GetStructuredTargetsWithHttpInfo(string? type = default, string? competition = default, int? pageSize = default, string? cursor = default, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStructuredTargetsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Structured Target
        /// </summary>
        /// <remarks>
        ///  Endpoint for getting data about a specific structured target by its ID.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="structuredTargetId">Structured target ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStructuredTargetResponse</returns>
        System.Threading.Tasks.Task<GetStructuredTargetResponse> GetStructuredTargetAsync(string structuredTargetId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Structured Target
        /// </summary>
        /// <remarks>
        ///  Endpoint for getting data about a specific structured target by its ID.
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="structuredTargetId">Structured target ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStructuredTargetResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetStructuredTargetResponse>> GetStructuredTargetWithHttpInfoAsync(string structuredTargetId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Structured Targets
        /// </summary>
        /// <remarks>
        /// Page size (min: 1, max: 2000)
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Filter by structured target type (optional)</param>
        /// <param name="competition">Filter by competition (optional)</param>
        /// <param name="pageSize">Number of items per page (min 1, max 2000, default 100) (optional, default to 100)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStructuredTargetsResponse</returns>
        System.Threading.Tasks.Task<GetStructuredTargetsResponse> GetStructuredTargetsAsync(string? type = default, string? competition = default, int? pageSize = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Structured Targets
        /// </summary>
        /// <remarks>
        /// Page size (min: 1, max: 2000)
        /// </remarks>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Filter by structured target type (optional)</param>
        /// <param name="competition">Filter by competition (optional)</param>
        /// <param name="pageSize">Number of items per page (min 1, max 2000, default 100) (optional, default to 100)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStructuredTargetsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetStructuredTargetsResponse>> GetStructuredTargetsWithHttpInfoAsync(string? type = default, string? competition = default, int? pageSize = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStructuredTargetsApi : IStructuredTargetsApiSync, IStructuredTargetsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StructuredTargetsApi : IStructuredTargetsApi
    {
        private Kalshi.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StructuredTargetsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StructuredTargetsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StructuredTargetsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StructuredTargetsApi(string basePath)
        {
            this.Configuration = Kalshi.Api.Client.Configuration.MergeConfigurations(
                Kalshi.Api.Client.GlobalConfiguration.Instance,
                new Kalshi.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StructuredTargetsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StructuredTargetsApi(Kalshi.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Kalshi.Api.Client.Configuration.MergeConfigurations(
                Kalshi.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Kalshi.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StructuredTargetsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public StructuredTargetsApi(Kalshi.Api.Client.ISynchronousClient client, Kalshi.Api.Client.IAsynchronousClient asyncClient, Kalshi.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Kalshi.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Kalshi.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Kalshi.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Kalshi.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Kalshi.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Structured Target  Endpoint for getting data about a specific structured target by its ID.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="structuredTargetId">Structured target ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStructuredTargetResponse</returns>
        public GetStructuredTargetResponse GetStructuredTarget(string structuredTargetId, int operationIndex = 0)
        {
            Kalshi.Api.Client.ApiResponse<GetStructuredTargetResponse> localVarResponse = GetStructuredTargetWithHttpInfo(structuredTargetId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Structured Target  Endpoint for getting data about a specific structured target by its ID.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="structuredTargetId">Structured target ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStructuredTargetResponse</returns>
        public Kalshi.Api.Client.ApiResponse<GetStructuredTargetResponse> GetStructuredTargetWithHttpInfo(string structuredTargetId, int operationIndex = 0)
        {
            // verify the required parameter 'structuredTargetId' is set
            if (structuredTargetId == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'structuredTargetId' when calling StructuredTargetsApi->GetStructuredTarget");
            }

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("structured_target_id", Kalshi.Api.Client.ClientUtils.ParameterToString(structuredTargetId)); // path parameter

            localVarRequestOptions.Operation = "StructuredTargetsApi.GetStructuredTarget";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<GetStructuredTargetResponse>("/structured_targets/{structured_target_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStructuredTarget", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Structured Target  Endpoint for getting data about a specific structured target by its ID.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="structuredTargetId">Structured target ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStructuredTargetResponse</returns>
        public async System.Threading.Tasks.Task<GetStructuredTargetResponse> GetStructuredTargetAsync(string structuredTargetId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Kalshi.Api.Client.ApiResponse<GetStructuredTargetResponse> localVarResponse = await GetStructuredTargetWithHttpInfoAsync(structuredTargetId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Structured Target  Endpoint for getting data about a specific structured target by its ID.
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="structuredTargetId">Structured target ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStructuredTargetResponse)</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<GetStructuredTargetResponse>> GetStructuredTargetWithHttpInfoAsync(string structuredTargetId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'structuredTargetId' is set
            if (structuredTargetId == null)
            {
                throw new Kalshi.Api.Client.ApiException(400, "Missing required parameter 'structuredTargetId' when calling StructuredTargetsApi->GetStructuredTarget");
            }


            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("structured_target_id", Kalshi.Api.Client.ClientUtils.ParameterToString(structuredTargetId)); // path parameter

            localVarRequestOptions.Operation = "StructuredTargetsApi.GetStructuredTarget";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetStructuredTargetResponse>("/structured_targets/{structured_target_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStructuredTarget", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Structured Targets Page size (min: 1, max: 2000)
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Filter by structured target type (optional)</param>
        /// <param name="competition">Filter by competition (optional)</param>
        /// <param name="pageSize">Number of items per page (min 1, max 2000, default 100) (optional, default to 100)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStructuredTargetsResponse</returns>
        public GetStructuredTargetsResponse GetStructuredTargets(string? type = default, string? competition = default, int? pageSize = default, string? cursor = default, int operationIndex = 0)
        {
            Kalshi.Api.Client.ApiResponse<GetStructuredTargetsResponse> localVarResponse = GetStructuredTargetsWithHttpInfo(type, competition, pageSize, cursor);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Structured Targets Page size (min: 1, max: 2000)
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Filter by structured target type (optional)</param>
        /// <param name="competition">Filter by competition (optional)</param>
        /// <param name="pageSize">Number of items per page (min 1, max 2000, default 100) (optional, default to 100)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStructuredTargetsResponse</returns>
        public Kalshi.Api.Client.ApiResponse<GetStructuredTargetsResponse> GetStructuredTargetsWithHttpInfo(string? type = default, string? competition = default, int? pageSize = default, string? cursor = default, int operationIndex = 0)
        {
            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }
            if (competition != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "competition", competition));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "page_size", pageSize));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "StructuredTargetsApi.GetStructuredTargets";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<GetStructuredTargetsResponse>("/structured_targets", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStructuredTargets", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Structured Targets Page size (min: 1, max: 2000)
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Filter by structured target type (optional)</param>
        /// <param name="competition">Filter by competition (optional)</param>
        /// <param name="pageSize">Number of items per page (min 1, max 2000, default 100) (optional, default to 100)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStructuredTargetsResponse</returns>
        public async System.Threading.Tasks.Task<GetStructuredTargetsResponse> GetStructuredTargetsAsync(string? type = default, string? competition = default, int? pageSize = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            Kalshi.Api.Client.ApiResponse<GetStructuredTargetsResponse> localVarResponse = await GetStructuredTargetsWithHttpInfoAsync(type, competition, pageSize, cursor, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Structured Targets Page size (min: 1, max: 2000)
        /// </summary>
        /// <exception cref="Kalshi.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="type">Filter by structured target type (optional)</param>
        /// <param name="competition">Filter by competition (optional)</param>
        /// <param name="pageSize">Number of items per page (min 1, max 2000, default 100) (optional, default to 100)</param>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStructuredTargetsResponse)</returns>
        public async System.Threading.Tasks.Task<Kalshi.Api.Client.ApiResponse<GetStructuredTargetsResponse>> GetStructuredTargetsWithHttpInfoAsync(string? type = default, string? competition = default, int? pageSize = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {

            Kalshi.Api.Client.RequestOptions localVarRequestOptions = new Kalshi.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Kalshi.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Kalshi.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }
            if (competition != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "competition", competition));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "page_size", pageSize));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kalshi.Api.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "StructuredTargetsApi.GetStructuredTargets";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetStructuredTargetsResponse>("/structured_targets", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStructuredTargets", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
