/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// AmendOrderResponse
    /// </summary>
    [DataContract(Name = "AmendOrderResponse")]
    public partial class AmendOrderResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AmendOrderResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AmendOrderResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AmendOrderResponse" /> class.
        /// </summary>
        /// <param name="oldOrder">oldOrder (required).</param>
        /// <param name="order">order (required).</param>
        public AmendOrderResponse(Order oldOrder = default, Order order = default)
        {
            // to ensure "oldOrder" is required (not null)
            if (oldOrder == null)
            {
                throw new ArgumentNullException("oldOrder is a required property for AmendOrderResponse and cannot be null");
            }
            this.OldOrder = oldOrder;
            // to ensure "order" is required (not null)
            if (order == null)
            {
                throw new ArgumentNullException("order is a required property for AmendOrderResponse and cannot be null");
            }
            this.Order = order;
        }

        /// <summary>
        /// Gets or Sets OldOrder
        /// </summary>
        [DataMember(Name = "old_order", IsRequired = true, EmitDefaultValue = true)]
        public Order OldOrder { get; set; }

        /// <summary>
        /// Gets or Sets Order
        /// </summary>
        [DataMember(Name = "order", IsRequired = true, EmitDefaultValue = true)]
        public Order Order { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AmendOrderResponse {\n");
            sb.Append("  OldOrder: ").Append(OldOrder).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
