/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// Announcement
    /// </summary>
    [DataContract(Name = "Announcement")]
    public partial class Announcement : IValidatableObject
    {
        /// <summary>
        /// The type of the announcement.
        /// </summary>
        /// <value>The type of the announcement.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Info for value: info
            /// </summary>
            [EnumMember(Value = "info")]
            Info = 1,

            /// <summary>
            /// Enum Warning for value: warning
            /// </summary>
            [EnumMember(Value = "warning")]
            Warning = 2,

            /// <summary>
            /// Enum Error for value: error
            /// </summary>
            [EnumMember(Value = "error")]
            Error = 3
        }


        /// <summary>
        /// The type of the announcement.
        /// </summary>
        /// <value>The type of the announcement.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// The current status of this announcement.
        /// </summary>
        /// <value>The current status of this announcement.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            [EnumMember(Value = "active")]
            Active = 1,

            /// <summary>
            /// Enum Inactive for value: inactive
            /// </summary>
            [EnumMember(Value = "inactive")]
            Inactive = 2
        }


        /// <summary>
        /// The current status of this announcement.
        /// </summary>
        /// <value>The current status of this announcement.</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Announcement" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Announcement() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Announcement" /> class.
        /// </summary>
        /// <param name="type">The type of the announcement. (required).</param>
        /// <param name="message">The message contained within the announcement. (required).</param>
        /// <param name="deliveryTime">The time the announcement was delivered. (required).</param>
        /// <param name="status">The current status of this announcement. (required).</param>
        public Announcement(TypeEnum type = default, string message = default, DateTime deliveryTime = default, StatusEnum status = default)
        {
            this.Type = type;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for Announcement and cannot be null");
            }
            this.Message = message;
            this.DeliveryTime = deliveryTime;
            this.Status = status;
        }

        /// <summary>
        /// The message contained within the announcement.
        /// </summary>
        /// <value>The message contained within the announcement.</value>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// The time the announcement was delivered.
        /// </summary>
        /// <value>The time the announcement was delivered.</value>
        [DataMember(Name = "delivery_time", IsRequired = true, EmitDefaultValue = true)]
        public DateTime DeliveryTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Announcement {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  DeliveryTime: ").Append(DeliveryTime).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
