/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// CreateApiKeyRequest
    /// </summary>
    [DataContract(Name = "CreateApiKeyRequest")]
    public partial class CreateApiKeyRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateApiKeyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateApiKeyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateApiKeyRequest" /> class.
        /// </summary>
        /// <param name="name">Name for the API key. This helps identify the key&#39;s purpose (required).</param>
        /// <param name="publicKey">RSA public key in PEM format. This will be used to verify signatures on API requests (required).</param>
        public CreateApiKeyRequest(string name = default, string publicKey = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateApiKeyRequest and cannot be null");
            }
            this.Name = name;
            // to ensure "publicKey" is required (not null)
            if (publicKey == null)
            {
                throw new ArgumentNullException("publicKey is a required property for CreateApiKeyRequest and cannot be null");
            }
            this.PublicKey = publicKey;
        }

        /// <summary>
        /// Name for the API key. This helps identify the key&#39;s purpose
        /// </summary>
        /// <value>Name for the API key. This helps identify the key&#39;s purpose</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// RSA public key in PEM format. This will be used to verify signatures on API requests
        /// </summary>
        /// <value>RSA public key in PEM format. This will be used to verify signatures on API requests</value>
        [DataMember(Name = "public_key", IsRequired = true, EmitDefaultValue = true)]
        public string PublicKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateApiKeyRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PublicKey: ").Append(PublicKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
