/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// CreateQuoteRequest
    /// </summary>
    [DataContract(Name = "CreateQuoteRequest")]
    public partial class CreateQuoteRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateQuoteRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateQuoteRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateQuoteRequest" /> class.
        /// </summary>
        /// <param name="rfqId">The ID of the RFQ to quote on (required).</param>
        /// <param name="yesBid">The bid price for YES contracts, in dollars (required).</param>
        /// <param name="noBid">The bid price for NO contracts, in dollars (required).</param>
        /// <param name="restRemainder">Whether to rest the remainder of the quote after execution (required).</param>
        public CreateQuoteRequest(string rfqId = default, string yesBid = default, string noBid = default, bool restRemainder = default)
        {
            // to ensure "rfqId" is required (not null)
            if (rfqId == null)
            {
                throw new ArgumentNullException("rfqId is a required property for CreateQuoteRequest and cannot be null");
            }
            this.RfqId = rfqId;
            // to ensure "yesBid" is required (not null)
            if (yesBid == null)
            {
                throw new ArgumentNullException("yesBid is a required property for CreateQuoteRequest and cannot be null");
            }
            this.YesBid = yesBid;
            // to ensure "noBid" is required (not null)
            if (noBid == null)
            {
                throw new ArgumentNullException("noBid is a required property for CreateQuoteRequest and cannot be null");
            }
            this.NoBid = noBid;
            this.RestRemainder = restRemainder;
        }

        /// <summary>
        /// The ID of the RFQ to quote on
        /// </summary>
        /// <value>The ID of the RFQ to quote on</value>
        [DataMember(Name = "rfq_id", IsRequired = true, EmitDefaultValue = true)]
        public string RfqId { get; set; }

        /// <summary>
        /// The bid price for YES contracts, in dollars
        /// </summary>
        /// <value>The bid price for YES contracts, in dollars</value>
        [DataMember(Name = "yes_bid", IsRequired = true, EmitDefaultValue = true)]
        public string YesBid { get; set; }

        /// <summary>
        /// The bid price for NO contracts, in dollars
        /// </summary>
        /// <value>The bid price for NO contracts, in dollars</value>
        [DataMember(Name = "no_bid", IsRequired = true, EmitDefaultValue = true)]
        public string NoBid { get; set; }

        /// <summary>
        /// Whether to rest the remainder of the quote after execution
        /// </summary>
        /// <value>Whether to rest the remainder of the quote after execution</value>
        [DataMember(Name = "rest_remainder", IsRequired = true, EmitDefaultValue = true)]
        public bool RestRemainder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateQuoteRequest {\n");
            sb.Append("  RfqId: ").Append(RfqId).Append("\n");
            sb.Append("  YesBid: ").Append(YesBid).Append("\n");
            sb.Append("  NoBid: ").Append(NoBid).Append("\n");
            sb.Append("  RestRemainder: ").Append(RestRemainder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
