/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// CreateMarketInMultivariateEventCollectionResponse
    /// </summary>
    [DataContract(Name = "CreateMarketInMultivariateEventCollectionResponse")]
    public partial class CreateMarketInMultivariateEventCollectionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateMarketInMultivariateEventCollectionResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateMarketInMultivariateEventCollectionResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateMarketInMultivariateEventCollectionResponse" /> class.
        /// </summary>
        /// <param name="eventTicker">Event ticker for the created market. (required).</param>
        /// <param name="marketTicker">Market ticker for the created market. (required).</param>
        public CreateMarketInMultivariateEventCollectionResponse(string eventTicker = default, string marketTicker = default)
        {
            // to ensure "eventTicker" is required (not null)
            if (eventTicker == null)
            {
                throw new ArgumentNullException("eventTicker is a required property for CreateMarketInMultivariateEventCollectionResponse and cannot be null");
            }
            this.EventTicker = eventTicker;
            // to ensure "marketTicker" is required (not null)
            if (marketTicker == null)
            {
                throw new ArgumentNullException("marketTicker is a required property for CreateMarketInMultivariateEventCollectionResponse and cannot be null");
            }
            this.MarketTicker = marketTicker;
        }

        /// <summary>
        /// Event ticker for the created market.
        /// </summary>
        /// <value>Event ticker for the created market.</value>
        [DataMember(Name = "event_ticker", IsRequired = true, EmitDefaultValue = true)]
        public string EventTicker { get; set; }

        /// <summary>
        /// Market ticker for the created market.
        /// </summary>
        /// <value>Market ticker for the created market.</value>
        [DataMember(Name = "market_ticker", IsRequired = true, EmitDefaultValue = true)]
        public string MarketTicker { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateMarketInMultivariateEventCollectionResponse {\n");
            sb.Append("  EventTicker: ").Append(EventTicker).Append("\n");
            sb.Append("  MarketTicker: ").Append(MarketTicker).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
