/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// EventData
    /// </summary>
    [DataContract(Name = "EventData")]
    public partial class EventData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventData" /> class.
        /// </summary>
        /// <param name="eventTicker">Unique identifier for this event. (required).</param>
        /// <param name="seriesTicker">Unique identifier for the series this event belongs to. (required).</param>
        /// <param name="subTitle">Shortened descriptive title for the event. (required).</param>
        /// <param name="title">Full title of the event. (required).</param>
        /// <param name="collateralReturnType">Specifies how collateral is returned when markets settle (e.g., &#39;binary&#39; for standard yes/no markets). (required).</param>
        /// <param name="mutuallyExclusive">If true, only one market in this event can resolve to &#39;yes&#39;. If false, multiple markets can resolve to &#39;yes&#39;. (required).</param>
        /// <param name="category">Event category (deprecated, use series-level category instead). (required).</param>
        /// <param name="strikeDate">The specific date this event is based on. Only filled when the event uses a date strike (mutually exclusive with strike_period)..</param>
        /// <param name="strikePeriod">The time period this event covers (e.g., &#39;week&#39;, &#39;month&#39;). Only filled when the event uses a period strike (mutually exclusive with strike_date)..</param>
        /// <param name="markets">Array of markets associated with this event. Only populated when &#39;with_nested_markets&#x3D;true&#39; is specified in the request..</param>
        /// <param name="availableOnBrokers">Whether this event is available to trade on brokers. (required).</param>
        /// <param name="productMetadata">Additional metadata for the event. (required).</param>
        public EventData(string eventTicker = default, string seriesTicker = default, string subTitle = default, string title = default, string collateralReturnType = default, bool mutuallyExclusive = default, string category = default, DateTime? strikeDate = default, string strikePeriod = default, List<Market> markets = default, bool availableOnBrokers = default, Object productMetadata = default)
        {
            // to ensure "eventTicker" is required (not null)
            if (eventTicker == null)
            {
                throw new ArgumentNullException("eventTicker is a required property for EventData and cannot be null");
            }
            this.EventTicker = eventTicker;
            // to ensure "seriesTicker" is required (not null)
            if (seriesTicker == null)
            {
                throw new ArgumentNullException("seriesTicker is a required property for EventData and cannot be null");
            }
            this.SeriesTicker = seriesTicker;
            // to ensure "subTitle" is required (not null)
            if (subTitle == null)
            {
                throw new ArgumentNullException("subTitle is a required property for EventData and cannot be null");
            }
            this.SubTitle = subTitle;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for EventData and cannot be null");
            }
            this.Title = title;
            // to ensure "collateralReturnType" is required (not null)
            if (collateralReturnType == null)
            {
                throw new ArgumentNullException("collateralReturnType is a required property for EventData and cannot be null");
            }
            this.CollateralReturnType = collateralReturnType;
            this.MutuallyExclusive = mutuallyExclusive;
            // to ensure "category" is required (not null)
            if (category == null)
            {
                throw new ArgumentNullException("category is a required property for EventData and cannot be null");
            }
            this.Category = category;
            this.AvailableOnBrokers = availableOnBrokers;
            // to ensure "productMetadata" is required (not null)
            if (productMetadata == null)
            {
                throw new ArgumentNullException("productMetadata is a required property for EventData and cannot be null");
            }
            this.ProductMetadata = productMetadata;
            this.StrikeDate = strikeDate;
            this.StrikePeriod = strikePeriod;
            this.Markets = markets;
        }

        /// <summary>
        /// Unique identifier for this event.
        /// </summary>
        /// <value>Unique identifier for this event.</value>
        [DataMember(Name = "event_ticker", IsRequired = true, EmitDefaultValue = true)]
        public string EventTicker { get; set; }

        /// <summary>
        /// Unique identifier for the series this event belongs to.
        /// </summary>
        /// <value>Unique identifier for the series this event belongs to.</value>
        [DataMember(Name = "series_ticker", IsRequired = true, EmitDefaultValue = true)]
        public string SeriesTicker { get; set; }

        /// <summary>
        /// Shortened descriptive title for the event.
        /// </summary>
        /// <value>Shortened descriptive title for the event.</value>
        [DataMember(Name = "sub_title", IsRequired = true, EmitDefaultValue = true)]
        public string SubTitle { get; set; }

        /// <summary>
        /// Full title of the event.
        /// </summary>
        /// <value>Full title of the event.</value>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Specifies how collateral is returned when markets settle (e.g., &#39;binary&#39; for standard yes/no markets).
        /// </summary>
        /// <value>Specifies how collateral is returned when markets settle (e.g., &#39;binary&#39; for standard yes/no markets).</value>
        [DataMember(Name = "collateral_return_type", IsRequired = true, EmitDefaultValue = true)]
        public string CollateralReturnType { get; set; }

        /// <summary>
        /// If true, only one market in this event can resolve to &#39;yes&#39;. If false, multiple markets can resolve to &#39;yes&#39;.
        /// </summary>
        /// <value>If true, only one market in this event can resolve to &#39;yes&#39;. If false, multiple markets can resolve to &#39;yes&#39;.</value>
        [DataMember(Name = "mutually_exclusive", IsRequired = true, EmitDefaultValue = true)]
        public bool MutuallyExclusive { get; set; }

        /// <summary>
        /// Event category (deprecated, use series-level category instead).
        /// </summary>
        /// <value>Event category (deprecated, use series-level category instead).</value>
        [DataMember(Name = "category", IsRequired = true, EmitDefaultValue = true)]
        public string Category { get; set; }

        /// <summary>
        /// The specific date this event is based on. Only filled when the event uses a date strike (mutually exclusive with strike_period).
        /// </summary>
        /// <value>The specific date this event is based on. Only filled when the event uses a date strike (mutually exclusive with strike_period).</value>
        [DataMember(Name = "strike_date", EmitDefaultValue = true)]
        public DateTime? StrikeDate { get; set; }

        /// <summary>
        /// The time period this event covers (e.g., &#39;week&#39;, &#39;month&#39;). Only filled when the event uses a period strike (mutually exclusive with strike_date).
        /// </summary>
        /// <value>The time period this event covers (e.g., &#39;week&#39;, &#39;month&#39;). Only filled when the event uses a period strike (mutually exclusive with strike_date).</value>
        [DataMember(Name = "strike_period", EmitDefaultValue = true)]
        public string StrikePeriod { get; set; }

        /// <summary>
        /// Array of markets associated with this event. Only populated when &#39;with_nested_markets&#x3D;true&#39; is specified in the request.
        /// </summary>
        /// <value>Array of markets associated with this event. Only populated when &#39;with_nested_markets&#x3D;true&#39; is specified in the request.</value>
        [DataMember(Name = "markets", EmitDefaultValue = false)]
        public List<Market> Markets { get; set; }

        /// <summary>
        /// Whether this event is available to trade on brokers.
        /// </summary>
        /// <value>Whether this event is available to trade on brokers.</value>
        [DataMember(Name = "available_on_brokers", IsRequired = true, EmitDefaultValue = true)]
        public bool AvailableOnBrokers { get; set; }

        /// <summary>
        /// Additional metadata for the event.
        /// </summary>
        /// <value>Additional metadata for the event.</value>
        [DataMember(Name = "product_metadata", IsRequired = true, EmitDefaultValue = true)]
        public Object ProductMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventData {\n");
            sb.Append("  EventTicker: ").Append(EventTicker).Append("\n");
            sb.Append("  SeriesTicker: ").Append(SeriesTicker).Append("\n");
            sb.Append("  SubTitle: ").Append(SubTitle).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  CollateralReturnType: ").Append(CollateralReturnType).Append("\n");
            sb.Append("  MutuallyExclusive: ").Append(MutuallyExclusive).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  StrikeDate: ").Append(StrikeDate).Append("\n");
            sb.Append("  StrikePeriod: ").Append(StrikePeriod).Append("\n");
            sb.Append("  Markets: ").Append(Markets).Append("\n");
            sb.Append("  AvailableOnBrokers: ").Append(AvailableOnBrokers).Append("\n");
            sb.Append("  ProductMetadata: ").Append(ProductMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
