/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// EventPosition
    /// </summary>
    [DataContract(Name = "EventPosition")]
    public partial class EventPosition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventPosition" /> class.
        /// </summary>
        /// <param name="eventTicker">Unique identifier for events.</param>
        /// <param name="totalCost">Total spent on this event in cents.</param>
        /// <param name="totalCostDollars">Total spent on this event in dollars.</param>
        /// <param name="totalCostShares">Total number of shares traded on this event (including both YES and NO contracts).</param>
        /// <param name="eventExposure">Cost of the aggregate event position in cents.</param>
        /// <param name="eventExposureDollars">Cost of the aggregate event position in dollars.</param>
        /// <param name="realizedPnl">Locked in profit and loss, in cents.</param>
        /// <param name="realizedPnlDollars">Locked in profit and loss, in dollars.</param>
        /// <param name="restingOrderCount">[DEPRECATED] Aggregate size of resting orders in contract units.</param>
        /// <param name="feesPaid">Fees paid on fill orders, in cents.</param>
        /// <param name="feesPaidDollars">Fees paid on fill orders, in dollars.</param>
        public EventPosition(string eventTicker = default, int totalCost = default, string totalCostDollars = default, long totalCostShares = default, int eventExposure = default, string eventExposureDollars = default, int realizedPnl = default, string realizedPnlDollars = default, int restingOrderCount = default, int feesPaid = default, string feesPaidDollars = default)
        {
            this.EventTicker = eventTicker;
            this.TotalCost = totalCost;
            this.TotalCostDollars = totalCostDollars;
            this.TotalCostShares = totalCostShares;
            this.EventExposure = eventExposure;
            this.EventExposureDollars = eventExposureDollars;
            this.RealizedPnl = realizedPnl;
            this.RealizedPnlDollars = realizedPnlDollars;
            this.RestingOrderCount = restingOrderCount;
            this.FeesPaid = feesPaid;
            this.FeesPaidDollars = feesPaidDollars;
        }

        /// <summary>
        /// Unique identifier for events
        /// </summary>
        /// <value>Unique identifier for events</value>
        [DataMember(Name = "event_ticker", EmitDefaultValue = false)]
        public string EventTicker { get; set; }

        /// <summary>
        /// Total spent on this event in cents
        /// </summary>
        /// <value>Total spent on this event in cents</value>
        [DataMember(Name = "total_cost", EmitDefaultValue = false)]
        public int TotalCost { get; set; }

        /// <summary>
        /// Total spent on this event in dollars
        /// </summary>
        /// <value>Total spent on this event in dollars</value>
        [DataMember(Name = "total_cost_dollars", EmitDefaultValue = false)]
        public string TotalCostDollars { get; set; }

        /// <summary>
        /// Total number of shares traded on this event (including both YES and NO contracts)
        /// </summary>
        /// <value>Total number of shares traded on this event (including both YES and NO contracts)</value>
        [DataMember(Name = "total_cost_shares", EmitDefaultValue = false)]
        public long TotalCostShares { get; set; }

        /// <summary>
        /// Cost of the aggregate event position in cents
        /// </summary>
        /// <value>Cost of the aggregate event position in cents</value>
        [DataMember(Name = "event_exposure", EmitDefaultValue = false)]
        public int EventExposure { get; set; }

        /// <summary>
        /// Cost of the aggregate event position in dollars
        /// </summary>
        /// <value>Cost of the aggregate event position in dollars</value>
        [DataMember(Name = "event_exposure_dollars", EmitDefaultValue = false)]
        public string EventExposureDollars { get; set; }

        /// <summary>
        /// Locked in profit and loss, in cents
        /// </summary>
        /// <value>Locked in profit and loss, in cents</value>
        [DataMember(Name = "realized_pnl", EmitDefaultValue = false)]
        public int RealizedPnl { get; set; }

        /// <summary>
        /// Locked in profit and loss, in dollars
        /// </summary>
        /// <value>Locked in profit and loss, in dollars</value>
        [DataMember(Name = "realized_pnl_dollars", EmitDefaultValue = false)]
        public string RealizedPnlDollars { get; set; }

        /// <summary>
        /// [DEPRECATED] Aggregate size of resting orders in contract units
        /// </summary>
        /// <value>[DEPRECATED] Aggregate size of resting orders in contract units</value>
        [DataMember(Name = "resting_order_count", EmitDefaultValue = false)]
        public int RestingOrderCount { get; set; }

        /// <summary>
        /// Fees paid on fill orders, in cents
        /// </summary>
        /// <value>Fees paid on fill orders, in cents</value>
        [DataMember(Name = "fees_paid", EmitDefaultValue = false)]
        public int FeesPaid { get; set; }

        /// <summary>
        /// Fees paid on fill orders, in dollars
        /// </summary>
        /// <value>Fees paid on fill orders, in dollars</value>
        [DataMember(Name = "fees_paid_dollars", EmitDefaultValue = false)]
        public string FeesPaidDollars { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventPosition {\n");
            sb.Append("  EventTicker: ").Append(EventTicker).Append("\n");
            sb.Append("  TotalCost: ").Append(TotalCost).Append("\n");
            sb.Append("  TotalCostDollars: ").Append(TotalCostDollars).Append("\n");
            sb.Append("  TotalCostShares: ").Append(TotalCostShares).Append("\n");
            sb.Append("  EventExposure: ").Append(EventExposure).Append("\n");
            sb.Append("  EventExposureDollars: ").Append(EventExposureDollars).Append("\n");
            sb.Append("  RealizedPnl: ").Append(RealizedPnl).Append("\n");
            sb.Append("  RealizedPnlDollars: ").Append(RealizedPnlDollars).Append("\n");
            sb.Append("  RestingOrderCount: ").Append(RestingOrderCount).Append("\n");
            sb.Append("  FeesPaid: ").Append(FeesPaid).Append("\n");
            sb.Append("  FeesPaidDollars: ").Append(FeesPaidDollars).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
