/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetEventsCandlesticksResponseEventsInner
    /// </summary>
    [DataContract(Name = "GetEventsCandlesticksResponse_events_inner")]
    public partial class GetEventsCandlesticksResponseEventsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEventsCandlesticksResponseEventsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetEventsCandlesticksResponseEventsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEventsCandlesticksResponseEventsInner" /> class.
        /// </summary>
        /// <param name="eventTicker">The event ticker (required).</param>
        /// <param name="marketTickers">Array of market tickers in the event. (required).</param>
        /// <param name="marketCandlesticks">Array of market candlestick arrays, one for each market in the event. (required).</param>
        /// <param name="adjustedEndTs">Adjusted end timestamp if the requested candlesticks would be larger than maxAggregateCandidates. (required).</param>
        public GetEventsCandlesticksResponseEventsInner(string eventTicker = default, List<string> marketTickers = default, List<List<MarketCandlestick>> marketCandlesticks = default, long adjustedEndTs = default)
        {
            // to ensure "eventTicker" is required (not null)
            if (eventTicker == null)
            {
                throw new ArgumentNullException("eventTicker is a required property for GetEventsCandlesticksResponseEventsInner and cannot be null");
            }
            this.EventTicker = eventTicker;
            // to ensure "marketTickers" is required (not null)
            if (marketTickers == null)
            {
                throw new ArgumentNullException("marketTickers is a required property for GetEventsCandlesticksResponseEventsInner and cannot be null");
            }
            this.MarketTickers = marketTickers;
            // to ensure "marketCandlesticks" is required (not null)
            if (marketCandlesticks == null)
            {
                throw new ArgumentNullException("marketCandlesticks is a required property for GetEventsCandlesticksResponseEventsInner and cannot be null");
            }
            this.MarketCandlesticks = marketCandlesticks;
            this.AdjustedEndTs = adjustedEndTs;
        }

        /// <summary>
        /// The event ticker
        /// </summary>
        /// <value>The event ticker</value>
        [DataMember(Name = "event_ticker", IsRequired = true, EmitDefaultValue = true)]
        public string EventTicker { get; set; }

        /// <summary>
        /// Array of market tickers in the event.
        /// </summary>
        /// <value>Array of market tickers in the event.</value>
        [DataMember(Name = "market_tickers", IsRequired = true, EmitDefaultValue = true)]
        public List<string> MarketTickers { get; set; }

        /// <summary>
        /// Array of market candlestick arrays, one for each market in the event.
        /// </summary>
        /// <value>Array of market candlestick arrays, one for each market in the event.</value>
        [DataMember(Name = "market_candlesticks", IsRequired = true, EmitDefaultValue = true)]
        public List<List<MarketCandlestick>> MarketCandlesticks { get; set; }

        /// <summary>
        /// Adjusted end timestamp if the requested candlesticks would be larger than maxAggregateCandidates.
        /// </summary>
        /// <value>Adjusted end timestamp if the requested candlesticks would be larger than maxAggregateCandidates.</value>
        [DataMember(Name = "adjusted_end_ts", IsRequired = true, EmitDefaultValue = true)]
        public long AdjustedEndTs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEventsCandlesticksResponseEventsInner {\n");
            sb.Append("  EventTicker: ").Append(EventTicker).Append("\n");
            sb.Append("  MarketTickers: ").Append(MarketTickers).Append("\n");
            sb.Append("  MarketCandlesticks: ").Append(MarketCandlesticks).Append("\n");
            sb.Append("  AdjustedEndTs: ").Append(AdjustedEndTs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
