/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetEventResponse
    /// </summary>
    [DataContract(Name = "GetEventResponse")]
    public partial class GetEventResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEventResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetEventResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEventResponse" /> class.
        /// </summary>
        /// <param name="varEvent">varEvent (required).</param>
        /// <param name="markets">Data for the markets in this event. This field is deprecated in favour of the \&quot;markets\&quot; field inside the event. Which will be filled with the same value if you use the query parameter \&quot;with_nested_markets&#x3D;true\&quot;. (required).</param>
        public GetEventResponse(EventData varEvent = default, List<Market> markets = default)
        {
            // to ensure "varEvent" is required (not null)
            if (varEvent == null)
            {
                throw new ArgumentNullException("varEvent is a required property for GetEventResponse and cannot be null");
            }
            this.Event = varEvent;
            // to ensure "markets" is required (not null)
            if (markets == null)
            {
                throw new ArgumentNullException("markets is a required property for GetEventResponse and cannot be null");
            }
            this.Markets = markets;
        }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = true)]
        public EventData Event { get; set; }

        /// <summary>
        /// Data for the markets in this event. This field is deprecated in favour of the \&quot;markets\&quot; field inside the event. Which will be filled with the same value if you use the query parameter \&quot;with_nested_markets&#x3D;true\&quot;.
        /// </summary>
        /// <value>Data for the markets in this event. This field is deprecated in favour of the \&quot;markets\&quot; field inside the event. Which will be filled with the same value if you use the query parameter \&quot;with_nested_markets&#x3D;true\&quot;.</value>
        [DataMember(Name = "markets", IsRequired = true, EmitDefaultValue = true)]
        public List<Market> Markets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEventResponse {\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  Markets: ").Append(Markets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
