/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetEventMetadataResponse
    /// </summary>
    [DataContract(Name = "GetEventMetadataResponse")]
    public partial class GetEventMetadataResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEventMetadataResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetEventMetadataResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEventMetadataResponse" /> class.
        /// </summary>
        /// <param name="imageUrl">A path to an image that represents this event. (required).</param>
        /// <param name="featuredImageUrl">A path to an image that represents the image of the featured market..</param>
        /// <param name="marketDetails">Metadata for the markets in this event. (required).</param>
        /// <param name="settlementSources">A list of settlement sources for this event. (required).</param>
        /// <param name="competition">Event competition..</param>
        /// <param name="competitionScope">Event scope, based on the competition..</param>
        public GetEventMetadataResponse(string imageUrl = default, string featuredImageUrl = default, List<MarketMetadata> marketDetails = default, List<SettlementSource> settlementSources = default, string competition = default, string competitionScope = default)
        {
            // to ensure "imageUrl" is required (not null)
            if (imageUrl == null)
            {
                throw new ArgumentNullException("imageUrl is a required property for GetEventMetadataResponse and cannot be null");
            }
            this.ImageUrl = imageUrl;
            // to ensure "marketDetails" is required (not null)
            if (marketDetails == null)
            {
                throw new ArgumentNullException("marketDetails is a required property for GetEventMetadataResponse and cannot be null");
            }
            this.MarketDetails = marketDetails;
            // to ensure "settlementSources" is required (not null)
            if (settlementSources == null)
            {
                throw new ArgumentNullException("settlementSources is a required property for GetEventMetadataResponse and cannot be null");
            }
            this.SettlementSources = settlementSources;
            this.FeaturedImageUrl = featuredImageUrl;
            this.Competition = competition;
            this.CompetitionScope = competitionScope;
        }

        /// <summary>
        /// A path to an image that represents this event.
        /// </summary>
        /// <value>A path to an image that represents this event.</value>
        [DataMember(Name = "image_url", IsRequired = true, EmitDefaultValue = true)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// A path to an image that represents the image of the featured market.
        /// </summary>
        /// <value>A path to an image that represents the image of the featured market.</value>
        [DataMember(Name = "featured_image_url", EmitDefaultValue = false)]
        public string FeaturedImageUrl { get; set; }

        /// <summary>
        /// Metadata for the markets in this event.
        /// </summary>
        /// <value>Metadata for the markets in this event.</value>
        [DataMember(Name = "market_details", IsRequired = true, EmitDefaultValue = true)]
        public List<MarketMetadata> MarketDetails { get; set; }

        /// <summary>
        /// A list of settlement sources for this event.
        /// </summary>
        /// <value>A list of settlement sources for this event.</value>
        [DataMember(Name = "settlement_sources", IsRequired = true, EmitDefaultValue = true)]
        public List<SettlementSource> SettlementSources { get; set; }

        /// <summary>
        /// Event competition.
        /// </summary>
        /// <value>Event competition.</value>
        [DataMember(Name = "competition", EmitDefaultValue = true)]
        public string Competition { get; set; }

        /// <summary>
        /// Event scope, based on the competition.
        /// </summary>
        /// <value>Event scope, based on the competition.</value>
        [DataMember(Name = "competition_scope", EmitDefaultValue = true)]
        public string CompetitionScope { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEventMetadataResponse {\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  FeaturedImageUrl: ").Append(FeaturedImageUrl).Append("\n");
            sb.Append("  MarketDetails: ").Append(MarketDetails).Append("\n");
            sb.Append("  SettlementSources: ").Append(SettlementSources).Append("\n");
            sb.Append("  Competition: ").Append(Competition).Append("\n");
            sb.Append("  CompetitionScope: ").Append(CompetitionScope).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
