/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetFiltersBySportsResponse
    /// </summary>
    [DataContract(Name = "GetFiltersBySportsResponse")]
    public partial class GetFiltersBySportsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetFiltersBySportsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetFiltersBySportsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetFiltersBySportsResponse" /> class.
        /// </summary>
        /// <param name="filtersBySports">Mapping of sports to their filter details (required).</param>
        /// <param name="sportOrdering">Ordered list of sports for display (required).</param>
        public GetFiltersBySportsResponse(Dictionary<string, SportFilterDetails> filtersBySports = default, List<string> sportOrdering = default)
        {
            // to ensure "filtersBySports" is required (not null)
            if (filtersBySports == null)
            {
                throw new ArgumentNullException("filtersBySports is a required property for GetFiltersBySportsResponse and cannot be null");
            }
            this.FiltersBySports = filtersBySports;
            // to ensure "sportOrdering" is required (not null)
            if (sportOrdering == null)
            {
                throw new ArgumentNullException("sportOrdering is a required property for GetFiltersBySportsResponse and cannot be null");
            }
            this.SportOrdering = sportOrdering;
        }

        /// <summary>
        /// Mapping of sports to their filter details
        /// </summary>
        /// <value>Mapping of sports to their filter details</value>
        [DataMember(Name = "filters_by_sports", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, SportFilterDetails> FiltersBySports { get; set; }

        /// <summary>
        /// Ordered list of sports for display
        /// </summary>
        /// <value>Ordered list of sports for display</value>
        [DataMember(Name = "sport_ordering", IsRequired = true, EmitDefaultValue = true)]
        public List<string> SportOrdering { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetFiltersBySportsResponse {\n");
            sb.Append("  FiltersBySports: ").Append(FiltersBySports).Append("\n");
            sb.Append("  SportOrdering: ").Append(SportOrdering).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
