/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetMarketOrderbookResponse
    /// </summary>
    [DataContract(Name = "GetMarketOrderbookResponse")]
    public partial class GetMarketOrderbookResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketOrderbookResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMarketOrderbookResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketOrderbookResponse" /> class.
        /// </summary>
        /// <param name="orderbook">orderbook (required).</param>
        public GetMarketOrderbookResponse(Orderbook orderbook = default)
        {
            // to ensure "orderbook" is required (not null)
            if (orderbook == null)
            {
                throw new ArgumentNullException("orderbook is a required property for GetMarketOrderbookResponse and cannot be null");
            }
            this.Orderbook = orderbook;
        }

        /// <summary>
        /// Gets or Sets Orderbook
        /// </summary>
        [DataMember(Name = "orderbook", IsRequired = true, EmitDefaultValue = true)]
        public Orderbook Orderbook { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMarketOrderbookResponse {\n");
            sb.Append("  Orderbook: ").Append(Orderbook).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
