/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetMarketsResponse
    /// </summary>
    [DataContract(Name = "GetMarketsResponse")]
    public partial class GetMarketsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMarketsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketsResponse" /> class.
        /// </summary>
        /// <param name="markets">markets (optional, defaults to empty list).</param>
        /// <param name="cursor">cursor (optional).</param>
        public GetMarketsResponse(List<Market>? markets = default, string? cursor = default)
        {
            // The upstream API occasionally returns error payloads without market data; fall back gracefully.
            this.Markets = markets ?? new List<Market>();
            this.Cursor = cursor;
        }

        /// <summary>
        /// Gets or Sets Markets
        /// </summary>
        [DataMember(Name = "markets", IsRequired = false, EmitDefaultValue = false)]
        public List<Market> Markets { get; set; } = new();

        /// <summary>
        /// Gets or Sets Cursor
        /// </summary>
        [DataMember(Name = "cursor", IsRequired = false, EmitDefaultValue = false)]
        public string? Cursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMarketsResponse {\n");
            sb.Append("  Markets: ").Append(Markets).Append("\n");
            sb.Append("  Cursor: ").Append(Cursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
