/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetMarketCandlesticksResponse
    /// </summary>
    [DataContract(Name = "GetMarketCandlesticksResponse")]
    public partial class GetMarketCandlesticksResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketCandlesticksResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMarketCandlesticksResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketCandlesticksResponse" /> class.
        /// </summary>
        /// <param name="ticker">Unique identifier for the market. (required).</param>
        /// <param name="candlesticks">Array of candlestick data points for the specified time range. (required).</param>
        public GetMarketCandlesticksResponse(string ticker = default, List<MarketCandlestick> candlesticks = default)
        {
            // to ensure "ticker" is required (not null)
            if (ticker == null)
            {
                throw new ArgumentNullException("ticker is a required property for GetMarketCandlesticksResponse and cannot be null");
            }
            this.Ticker = ticker;
            // to ensure "candlesticks" is required (not null)
            if (candlesticks == null)
            {
                throw new ArgumentNullException("candlesticks is a required property for GetMarketCandlesticksResponse and cannot be null");
            }
            this.Candlesticks = candlesticks;
        }

        /// <summary>
        /// Unique identifier for the market.
        /// </summary>
        /// <value>Unique identifier for the market.</value>
        [DataMember(Name = "ticker", IsRequired = true, EmitDefaultValue = true)]
        public string Ticker { get; set; }

        /// <summary>
        /// Array of candlestick data points for the specified time range.
        /// </summary>
        /// <value>Array of candlestick data points for the specified time range.</value>
        [DataMember(Name = "candlesticks", IsRequired = true, EmitDefaultValue = true)]
        public List<MarketCandlestick> Candlesticks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMarketCandlesticksResponse {\n");
            sb.Append("  Ticker: ").Append(Ticker).Append("\n");
            sb.Append("  Candlesticks: ").Append(Candlesticks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
