/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetMultivariateEventsResponse
    /// </summary>
    [DataContract(Name = "GetMultivariateEventsResponse")]
    public partial class GetMultivariateEventsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMultivariateEventsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMultivariateEventsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMultivariateEventsResponse" /> class.
        /// </summary>
        /// <param name="events">Array of multivariate events matching the query criteria. (required).</param>
        /// <param name="cursor">Pagination cursor for the next page. Empty if there are no more results. (required).</param>
        public GetMultivariateEventsResponse(List<EventData> events = default, string cursor = default)
        {
            // to ensure "events" is required (not null)
            if (events == null)
            {
                throw new ArgumentNullException("events is a required property for GetMultivariateEventsResponse and cannot be null");
            }
            this.Events = events;
            // to ensure "cursor" is required (not null)
            if (cursor == null)
            {
                throw new ArgumentNullException("cursor is a required property for GetMultivariateEventsResponse and cannot be null");
            }
            this.Cursor = cursor;
        }

        /// <summary>
        /// Array of multivariate events matching the query criteria.
        /// </summary>
        /// <value>Array of multivariate events matching the query criteria.</value>
        [DataMember(Name = "events", IsRequired = true, EmitDefaultValue = true)]
        public List<EventData> Events { get; set; }

        /// <summary>
        /// Pagination cursor for the next page. Empty if there are no more results.
        /// </summary>
        /// <value>Pagination cursor for the next page. Empty if there are no more results.</value>
        [DataMember(Name = "cursor", IsRequired = true, EmitDefaultValue = true)]
        public string Cursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMultivariateEventsResponse {\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  Cursor: ").Append(Cursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
