/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetMultivariateEventCollectionLookupHistoryResponse
    /// </summary>
    [DataContract(Name = "GetMultivariateEventCollectionLookupHistoryResponse")]
    public partial class GetMultivariateEventCollectionLookupHistoryResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMultivariateEventCollectionLookupHistoryResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMultivariateEventCollectionLookupHistoryResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMultivariateEventCollectionLookupHistoryResponse" /> class.
        /// </summary>
        /// <param name="lookupPoints">List of recent lookup points in the collection. (required).</param>
        public GetMultivariateEventCollectionLookupHistoryResponse(List<LookupPoint> lookupPoints = default)
        {
            // to ensure "lookupPoints" is required (not null)
            if (lookupPoints == null)
            {
                throw new ArgumentNullException("lookupPoints is a required property for GetMultivariateEventCollectionLookupHistoryResponse and cannot be null");
            }
            this.LookupPoints = lookupPoints;
        }

        /// <summary>
        /// List of recent lookup points in the collection.
        /// </summary>
        /// <value>List of recent lookup points in the collection.</value>
        [DataMember(Name = "lookup_points", IsRequired = true, EmitDefaultValue = true)]
        public List<LookupPoint> LookupPoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMultivariateEventCollectionLookupHistoryResponse {\n");
            sb.Append("  LookupPoints: ").Append(LookupPoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
