/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetRFQResponse
    /// </summary>
    [DataContract(Name = "GetRFQResponse")]
    public partial class GetRFQResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetRFQResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetRFQResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetRFQResponse" /> class.
        /// </summary>
        /// <param name="rfq">rfq (required).</param>
        public GetRFQResponse(RFQ rfq = default)
        {
            // to ensure "rfq" is required (not null)
            if (rfq == null)
            {
                throw new ArgumentNullException("rfq is a required property for GetRFQResponse and cannot be null");
            }
            this.Rfq = rfq;
        }

        /// <summary>
        /// Gets or Sets Rfq
        /// </summary>
        [DataMember(Name = "rfq", IsRequired = true, EmitDefaultValue = true)]
        public RFQ Rfq { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetRFQResponse {\n");
            sb.Append("  Rfq: ").Append(Rfq).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
