/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetTradesResponse
    /// </summary>
    [DataContract(Name = "GetTradesResponse")]
    public partial class GetTradesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetTradesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetTradesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetTradesResponse" /> class.
        /// </summary>
        /// <param name="trades">trades (required).</param>
        /// <param name="cursor">cursor (required).</param>
        public GetTradesResponse(List<Trade> trades = default, string cursor = default)
        {
            // to ensure "trades" is required (not null)
            if (trades == null)
            {
                throw new ArgumentNullException("trades is a required property for GetTradesResponse and cannot be null");
            }
            this.Trades = trades;
            // to ensure "cursor" is required (not null)
            if (cursor == null)
            {
                throw new ArgumentNullException("cursor is a required property for GetTradesResponse and cannot be null");
            }
            this.Cursor = cursor;
        }

        /// <summary>
        /// Gets or Sets Trades
        /// </summary>
        [DataMember(Name = "trades", IsRequired = true, EmitDefaultValue = true)]
        public List<Trade> Trades { get; set; }

        /// <summary>
        /// Gets or Sets Cursor
        /// </summary>
        [DataMember(Name = "cursor", IsRequired = true, EmitDefaultValue = true)]
        public string Cursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetTradesResponse {\n");
            sb.Append("  Trades: ").Append(Trades).Append("\n");
            sb.Append("  Cursor: ").Append(Cursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
