/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// GetTagsForSeriesCategoriesResponse
    /// </summary>
    [DataContract(Name = "GetTagsForSeriesCategoriesResponse")]
    public partial class GetTagsForSeriesCategoriesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetTagsForSeriesCategoriesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetTagsForSeriesCategoriesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetTagsForSeriesCategoriesResponse" /> class.
        /// </summary>
        /// <param name="tagsByCategories">Mapping of series categories to their associated tags (required).</param>
        public GetTagsForSeriesCategoriesResponse(Dictionary<string, List<string>> tagsByCategories = default)
        {
            // to ensure "tagsByCategories" is required (not null)
            if (tagsByCategories == null)
            {
                throw new ArgumentNullException("tagsByCategories is a required property for GetTagsForSeriesCategoriesResponse and cannot be null");
            }
            this.TagsByCategories = tagsByCategories;
        }

        /// <summary>
        /// Mapping of series categories to their associated tags
        /// </summary>
        /// <value>Mapping of series categories to their associated tags</value>
        [DataMember(Name = "tags_by_categories", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, List<string>> TagsByCategories { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetTagsForSeriesCategoriesResponse {\n");
            sb.Append("  TagsByCategories: ").Append(TagsByCategories).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
