/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// LookupTickersForMarketInMultivariateEventCollectionRequest
    /// </summary>
    [DataContract(Name = "LookupTickersForMarketInMultivariateEventCollectionRequest")]
    public partial class LookupTickersForMarketInMultivariateEventCollectionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LookupTickersForMarketInMultivariateEventCollectionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LookupTickersForMarketInMultivariateEventCollectionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LookupTickersForMarketInMultivariateEventCollectionRequest" /> class.
        /// </summary>
        /// <param name="selectedMarkets">List of selected markets that act as parameters to determine which market is produced. (required).</param>
        public LookupTickersForMarketInMultivariateEventCollectionRequest(List<TickerPair> selectedMarkets = default)
        {
            // to ensure "selectedMarkets" is required (not null)
            if (selectedMarkets == null)
            {
                throw new ArgumentNullException("selectedMarkets is a required property for LookupTickersForMarketInMultivariateEventCollectionRequest and cannot be null");
            }
            this.SelectedMarkets = selectedMarkets;
        }

        /// <summary>
        /// List of selected markets that act as parameters to determine which market is produced.
        /// </summary>
        /// <value>List of selected markets that act as parameters to determine which market is produced.</value>
        [DataMember(Name = "selected_markets", IsRequired = true, EmitDefaultValue = true)]
        public List<TickerPair> SelectedMarkets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LookupTickersForMarketInMultivariateEventCollectionRequest {\n");
            sb.Append("  SelectedMarkets: ").Append(SelectedMarkets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
