/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// Milestone
    /// </summary>
    [DataContract(Name = "Milestone")]
    public partial class Milestone : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Milestone" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Milestone() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Milestone" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the milestone. (required).</param>
        /// <param name="category">Category of the milestone. (required).</param>
        /// <param name="type">Type of the milestone. (required).</param>
        /// <param name="startDate">Start date of the milestone. (required).</param>
        /// <param name="endDate">End date of the milestone, if any..</param>
        /// <param name="relatedEventTickers">List of event tickers related to this milestone. (required).</param>
        /// <param name="title">Title of the milestone. (required).</param>
        /// <param name="notificationMessage">Notification message for the milestone. (required).</param>
        /// <param name="sourceId">Source id of milestone if available..</param>
        /// <param name="details">Additional details about the milestone. (required).</param>
        /// <param name="primaryEventTickers">List of event tickers directly related to the outcome of this milestone. (required).</param>
        /// <param name="lastUpdatedTs">Last time this structured target was updated. (required).</param>
        public Milestone(string id = default, string category = default, string type = default, DateTime startDate = default, DateTime? endDate = default, List<string> relatedEventTickers = default, string title = default, string notificationMessage = default, string sourceId = default, Dictionary<string, Object> details = default, List<string> primaryEventTickers = default, DateTime lastUpdatedTs = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Milestone and cannot be null");
            }
            this.Id = id;
            // to ensure "category" is required (not null)
            if (category == null)
            {
                throw new ArgumentNullException("category is a required property for Milestone and cannot be null");
            }
            this.Category = category;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for Milestone and cannot be null");
            }
            this.Type = type;
            this.StartDate = startDate;
            // to ensure "relatedEventTickers" is required (not null)
            if (relatedEventTickers == null)
            {
                throw new ArgumentNullException("relatedEventTickers is a required property for Milestone and cannot be null");
            }
            this.RelatedEventTickers = relatedEventTickers;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for Milestone and cannot be null");
            }
            this.Title = title;
            // to ensure "notificationMessage" is required (not null)
            if (notificationMessage == null)
            {
                throw new ArgumentNullException("notificationMessage is a required property for Milestone and cannot be null");
            }
            this.NotificationMessage = notificationMessage;
            // to ensure "details" is required (not null)
            if (details == null)
            {
                throw new ArgumentNullException("details is a required property for Milestone and cannot be null");
            }
            this.Details = details;
            // to ensure "primaryEventTickers" is required (not null)
            if (primaryEventTickers == null)
            {
                throw new ArgumentNullException("primaryEventTickers is a required property for Milestone and cannot be null");
            }
            this.PrimaryEventTickers = primaryEventTickers;
            this.LastUpdatedTs = lastUpdatedTs;
            this.EndDate = endDate;
            this.SourceId = sourceId;
        }

        /// <summary>
        /// Unique identifier for the milestone.
        /// </summary>
        /// <value>Unique identifier for the milestone.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Category of the milestone.
        /// </summary>
        /// <value>Category of the milestone.</value>
        [DataMember(Name = "category", IsRequired = true, EmitDefaultValue = true)]
        public string Category { get; set; }

        /// <summary>
        /// Type of the milestone.
        /// </summary>
        /// <value>Type of the milestone.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Start date of the milestone.
        /// </summary>
        /// <value>Start date of the milestone.</value>
        [DataMember(Name = "start_date", IsRequired = true, EmitDefaultValue = true)]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// End date of the milestone, if any.
        /// </summary>
        /// <value>End date of the milestone, if any.</value>
        [DataMember(Name = "end_date", EmitDefaultValue = true)]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// List of event tickers related to this milestone.
        /// </summary>
        /// <value>List of event tickers related to this milestone.</value>
        [DataMember(Name = "related_event_tickers", IsRequired = true, EmitDefaultValue = true)]
        public List<string> RelatedEventTickers { get; set; }

        /// <summary>
        /// Title of the milestone.
        /// </summary>
        /// <value>Title of the milestone.</value>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Notification message for the milestone.
        /// </summary>
        /// <value>Notification message for the milestone.</value>
        [DataMember(Name = "notification_message", IsRequired = true, EmitDefaultValue = true)]
        public string NotificationMessage { get; set; }

        /// <summary>
        /// Source id of milestone if available.
        /// </summary>
        /// <value>Source id of milestone if available.</value>
        [DataMember(Name = "source_id", EmitDefaultValue = true)]
        public string SourceId { get; set; }

        /// <summary>
        /// Additional details about the milestone.
        /// </summary>
        /// <value>Additional details about the milestone.</value>
        [DataMember(Name = "details", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Details { get; set; }

        /// <summary>
        /// List of event tickers directly related to the outcome of this milestone.
        /// </summary>
        /// <value>List of event tickers directly related to the outcome of this milestone.</value>
        [DataMember(Name = "primary_event_tickers", IsRequired = true, EmitDefaultValue = true)]
        public List<string> PrimaryEventTickers { get; set; }

        /// <summary>
        /// Last time this structured target was updated.
        /// </summary>
        /// <value>Last time this structured target was updated.</value>
        [DataMember(Name = "last_updated_ts", IsRequired = true, EmitDefaultValue = true)]
        public DateTime LastUpdatedTs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Milestone {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("  RelatedEventTickers: ").Append(RelatedEventTickers).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  NotificationMessage: ").Append(NotificationMessage).Append("\n");
            sb.Append("  SourceId: ").Append(SourceId).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("  PrimaryEventTickers: ").Append(PrimaryEventTickers).Append("\n");
            sb.Append("  LastUpdatedTs: ").Append(LastUpdatedTs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
