/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// MultivariateEventCollection
    /// </summary>
    [DataContract(Name = "MultivariateEventCollection")]
    public partial class MultivariateEventCollection : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultivariateEventCollection" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MultivariateEventCollection() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MultivariateEventCollection" /> class.
        /// </summary>
        /// <param name="collectionTicker">Unique identifier for the collection. (required).</param>
        /// <param name="seriesTicker">Series associated with the collection. Events produced in the collection will be associated with this series. (required).</param>
        /// <param name="title">Title of the collection. (required).</param>
        /// <param name="description">Short description of the collection. (required).</param>
        /// <param name="openDate">The open date of the collection. Before this time, the collection cannot be interacted with. (required).</param>
        /// <param name="closeDate">The close date of the collection. After this time, the collection cannot be interacted with. (required).</param>
        /// <param name="associatedEvents">List of events with their individual configuration. (required).</param>
        /// <param name="associatedEventTickers">[DEPRECATED - Use associated_events instead] A list of events associated with the collection. Markets in these events can be passed as inputs to the Lookup and Create endpoints. (required).</param>
        /// <param name="isOrdered">Whether the collection is ordered. If true, the order of markets passed into Lookup/Create affects the output. If false, the order does not matter. (required).</param>
        /// <param name="isSingleMarketPerEvent">[DEPRECATED - Use associated_events instead] Whether the collection accepts multiple markets from the same event passed into Lookup/Create. (required).</param>
        /// <param name="isAllYes">[DEPRECATED - Use associated_events instead] Whether the collection requires that only the market side of &#39;yes&#39; may be used. (required).</param>
        /// <param name="sizeMin">The minimum number of markets that must be passed into Lookup/Create (inclusive). (required).</param>
        /// <param name="sizeMax">The maximum number of markets that must be passed into Lookup/Create (inclusive). (required).</param>
        /// <param name="functionalDescription">A functional description of the collection describing how inputs affect the output. (required).</param>
        public MultivariateEventCollection(string collectionTicker = default, string seriesTicker = default, string title = default, string description = default, DateTime openDate = default, DateTime closeDate = default, List<AssociatedEvent> associatedEvents = default, List<string> associatedEventTickers = default, bool isOrdered = default, bool isSingleMarketPerEvent = default, bool isAllYes = default, int sizeMin = default, int sizeMax = default, string functionalDescription = default)
        {
            // to ensure "collectionTicker" is required (not null)
            if (collectionTicker == null)
            {
                throw new ArgumentNullException("collectionTicker is a required property for MultivariateEventCollection and cannot be null");
            }
            this.CollectionTicker = collectionTicker;
            // to ensure "seriesTicker" is required (not null)
            if (seriesTicker == null)
            {
                throw new ArgumentNullException("seriesTicker is a required property for MultivariateEventCollection and cannot be null");
            }
            this.SeriesTicker = seriesTicker;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for MultivariateEventCollection and cannot be null");
            }
            this.Title = title;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for MultivariateEventCollection and cannot be null");
            }
            this.Description = description;
            this.OpenDate = openDate;
            this.CloseDate = closeDate;
            // to ensure "associatedEvents" is required (not null)
            if (associatedEvents == null)
            {
                throw new ArgumentNullException("associatedEvents is a required property for MultivariateEventCollection and cannot be null");
            }
            this.AssociatedEvents = associatedEvents;
            // to ensure "associatedEventTickers" is required (not null)
            if (associatedEventTickers == null)
            {
                throw new ArgumentNullException("associatedEventTickers is a required property for MultivariateEventCollection and cannot be null");
            }
            this.AssociatedEventTickers = associatedEventTickers;
            this.IsOrdered = isOrdered;
            this.IsSingleMarketPerEvent = isSingleMarketPerEvent;
            this.IsAllYes = isAllYes;
            this.SizeMin = sizeMin;
            this.SizeMax = sizeMax;
            // to ensure "functionalDescription" is required (not null)
            if (functionalDescription == null)
            {
                throw new ArgumentNullException("functionalDescription is a required property for MultivariateEventCollection and cannot be null");
            }
            this.FunctionalDescription = functionalDescription;
        }

        /// <summary>
        /// Unique identifier for the collection.
        /// </summary>
        /// <value>Unique identifier for the collection.</value>
        [DataMember(Name = "collection_ticker", IsRequired = true, EmitDefaultValue = true)]
        public string CollectionTicker { get; set; }

        /// <summary>
        /// Series associated with the collection. Events produced in the collection will be associated with this series.
        /// </summary>
        /// <value>Series associated with the collection. Events produced in the collection will be associated with this series.</value>
        [DataMember(Name = "series_ticker", IsRequired = true, EmitDefaultValue = true)]
        public string SeriesTicker { get; set; }

        /// <summary>
        /// Title of the collection.
        /// </summary>
        /// <value>Title of the collection.</value>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Short description of the collection.
        /// </summary>
        /// <value>Short description of the collection.</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// The open date of the collection. Before this time, the collection cannot be interacted with.
        /// </summary>
        /// <value>The open date of the collection. Before this time, the collection cannot be interacted with.</value>
        [DataMember(Name = "open_date", IsRequired = true, EmitDefaultValue = true)]
        public DateTime OpenDate { get; set; }

        /// <summary>
        /// The close date of the collection. After this time, the collection cannot be interacted with.
        /// </summary>
        /// <value>The close date of the collection. After this time, the collection cannot be interacted with.</value>
        [DataMember(Name = "close_date", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CloseDate { get; set; }

        /// <summary>
        /// List of events with their individual configuration.
        /// </summary>
        /// <value>List of events with their individual configuration.</value>
        [DataMember(Name = "associated_events", IsRequired = true, EmitDefaultValue = true)]
        public List<AssociatedEvent> AssociatedEvents { get; set; }

        /// <summary>
        /// [DEPRECATED - Use associated_events instead] A list of events associated with the collection. Markets in these events can be passed as inputs to the Lookup and Create endpoints.
        /// </summary>
        /// <value>[DEPRECATED - Use associated_events instead] A list of events associated with the collection. Markets in these events can be passed as inputs to the Lookup and Create endpoints.</value>
        [DataMember(Name = "associated_event_tickers", IsRequired = true, EmitDefaultValue = true)]
        public List<string> AssociatedEventTickers { get; set; }

        /// <summary>
        /// Whether the collection is ordered. If true, the order of markets passed into Lookup/Create affects the output. If false, the order does not matter.
        /// </summary>
        /// <value>Whether the collection is ordered. If true, the order of markets passed into Lookup/Create affects the output. If false, the order does not matter.</value>
        [DataMember(Name = "is_ordered", IsRequired = true, EmitDefaultValue = true)]
        public bool IsOrdered { get; set; }

        /// <summary>
        /// [DEPRECATED - Use associated_events instead] Whether the collection accepts multiple markets from the same event passed into Lookup/Create.
        /// </summary>
        /// <value>[DEPRECATED - Use associated_events instead] Whether the collection accepts multiple markets from the same event passed into Lookup/Create.</value>
        [DataMember(Name = "is_single_market_per_event", IsRequired = true, EmitDefaultValue = true)]
        public bool IsSingleMarketPerEvent { get; set; }

        /// <summary>
        /// [DEPRECATED - Use associated_events instead] Whether the collection requires that only the market side of &#39;yes&#39; may be used.
        /// </summary>
        /// <value>[DEPRECATED - Use associated_events instead] Whether the collection requires that only the market side of &#39;yes&#39; may be used.</value>
        [DataMember(Name = "is_all_yes", IsRequired = true, EmitDefaultValue = true)]
        public bool IsAllYes { get; set; }

        /// <summary>
        /// The minimum number of markets that must be passed into Lookup/Create (inclusive).
        /// </summary>
        /// <value>The minimum number of markets that must be passed into Lookup/Create (inclusive).</value>
        [DataMember(Name = "size_min", IsRequired = true, EmitDefaultValue = true)]
        public int SizeMin { get; set; }

        /// <summary>
        /// The maximum number of markets that must be passed into Lookup/Create (inclusive).
        /// </summary>
        /// <value>The maximum number of markets that must be passed into Lookup/Create (inclusive).</value>
        [DataMember(Name = "size_max", IsRequired = true, EmitDefaultValue = true)]
        public int SizeMax { get; set; }

        /// <summary>
        /// A functional description of the collection describing how inputs affect the output.
        /// </summary>
        /// <value>A functional description of the collection describing how inputs affect the output.</value>
        [DataMember(Name = "functional_description", IsRequired = true, EmitDefaultValue = true)]
        public string FunctionalDescription { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MultivariateEventCollection {\n");
            sb.Append("  CollectionTicker: ").Append(CollectionTicker).Append("\n");
            sb.Append("  SeriesTicker: ").Append(SeriesTicker).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  OpenDate: ").Append(OpenDate).Append("\n");
            sb.Append("  CloseDate: ").Append(CloseDate).Append("\n");
            sb.Append("  AssociatedEvents: ").Append(AssociatedEvents).Append("\n");
            sb.Append("  AssociatedEventTickers: ").Append(AssociatedEventTickers).Append("\n");
            sb.Append("  IsOrdered: ").Append(IsOrdered).Append("\n");
            sb.Append("  IsSingleMarketPerEvent: ").Append(IsSingleMarketPerEvent).Append("\n");
            sb.Append("  IsAllYes: ").Append(IsAllYes).Append("\n");
            sb.Append("  SizeMin: ").Append(SizeMin).Append("\n");
            sb.Append("  SizeMax: ").Append(SizeMax).Append("\n");
            sb.Append("  FunctionalDescription: ").Append(FunctionalDescription).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
