/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// Order
    /// </summary>
    [DataContract(Name = "Order")]
    public partial class Order : IValidatableObject
    {
        /// <summary>
        /// Defines Side
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SideEnum
        {
            /// <summary>
            /// Enum Yes for value: yes
            /// </summary>
            [EnumMember(Value = "yes")]
            Yes = 1,

            /// <summary>
            /// Enum No for value: no
            /// </summary>
            [EnumMember(Value = "no")]
            No = 2
        }


        /// <summary>
        /// Gets or Sets Side
        /// </summary>
        [DataMember(Name = "side", IsRequired = true, EmitDefaultValue = true)]
        public SideEnum Side { get; set; }
        /// <summary>
        /// Defines Action
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActionEnum
        {
            /// <summary>
            /// Enum Buy for value: buy
            /// </summary>
            [EnumMember(Value = "buy")]
            Buy = 1,

            /// <summary>
            /// Enum Sell for value: sell
            /// </summary>
            [EnumMember(Value = "sell")]
            Sell = 2
        }


        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name = "action", IsRequired = true, EmitDefaultValue = true)]
        public ActionEnum Action { get; set; }
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Limit for value: limit
            /// </summary>
            [EnumMember(Value = "limit")]
            Limit = 1,

            /// <summary>
            /// Enum Market for value: market
            /// </summary>
            [EnumMember(Value = "market")]
            Market = 2
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public OrderStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets SelfTradePreventionType
        /// </summary>
        [DataMember(Name = "self_trade_prevention_type", EmitDefaultValue = false)]
        public SelfTradePreventionType? SelfTradePreventionType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Order" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Order() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Order" /> class.
        /// </summary>
        /// <param name="orderId">orderId (required).</param>
        /// <param name="userId">Unique identifier for users (required).</param>
        /// <param name="clientOrderId">clientOrderId (required).</param>
        /// <param name="ticker">ticker (required).</param>
        /// <param name="side">side (required).</param>
        /// <param name="action">action (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="yesPrice">yesPrice (required).</param>
        /// <param name="noPrice">noPrice (required).</param>
        /// <param name="yesPriceDollars">The yes price for this order in fixed-point dollars (required).</param>
        /// <param name="noPriceDollars">The no price for this order in fixed-point dollars (required).</param>
        /// <param name="fillCount">The number of contracts that have been filled (required).</param>
        /// <param name="remainingCount">remainingCount (required).</param>
        /// <param name="initialCount">The initial size of the order (contract units) (required).</param>
        /// <param name="takerFees">Fees paid on filled taker contracts, in cents (required).</param>
        /// <param name="makerFees">Fees paid on filled maker contracts, in cents (required).</param>
        /// <param name="takerFillCost">The cost of filled taker orders in cents (required).</param>
        /// <param name="makerFillCost">The cost of filled maker orders in cents (required).</param>
        /// <param name="takerFillCostDollars">The cost of filled taker orders in dollars (required).</param>
        /// <param name="makerFillCostDollars">The cost of filled maker orders in dollars (required).</param>
        /// <param name="queuePosition">**DEPRECATED**: This field is deprecated and will always return 0. Please use the GET /portfolio/orders/{order_id}/queue_position endpoint instead (required).</param>
        /// <param name="takerFeesDollars">Fees paid on filled taker contracts, in dollars.</param>
        /// <param name="makerFeesDollars">Fees paid on filled maker contracts, in dollars.</param>
        /// <param name="expirationTime">expirationTime.</param>
        /// <param name="createdTime">createdTime.</param>
        /// <param name="lastUpdateTime">The last update to an order (modify, cancel, fill).</param>
        /// <param name="selfTradePreventionType">selfTradePreventionType.</param>
        /// <param name="orderGroupId">The order group this order is part of.</param>
        /// <param name="cancelOrderOnPause">If this flag is set to true, the order will be canceled if the order is open and trading on the exchange is paused for any reason..</param>
        public Order(string orderId = default, string userId = default, string clientOrderId = default, string ticker = default, SideEnum side = default, ActionEnum action = default, TypeEnum type = default, OrderStatus status = default, int yesPrice = default, int noPrice = default, string yesPriceDollars = default, string noPriceDollars = default, int fillCount = default, int remainingCount = default, int initialCount = default, int takerFees = default, int makerFees = default, int takerFillCost = default, int makerFillCost = default, string takerFillCostDollars = default, string makerFillCostDollars = default, int queuePosition = default, string takerFeesDollars = default, string makerFeesDollars = default, DateTime? expirationTime = default, DateTime? createdTime = default, DateTime? lastUpdateTime = default, SelfTradePreventionType? selfTradePreventionType = default, string orderGroupId = default, bool cancelOrderOnPause = default)
        {
            // to ensure "orderId" is required (not null)
            if (orderId == null)
            {
                throw new ArgumentNullException("orderId is a required property for Order and cannot be null");
            }
            this.OrderId = orderId;
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new ArgumentNullException("userId is a required property for Order and cannot be null");
            }
            this.UserId = userId;
            // to ensure "clientOrderId" is required (not null)
            if (clientOrderId == null)
            {
                throw new ArgumentNullException("clientOrderId is a required property for Order and cannot be null");
            }
            this.ClientOrderId = clientOrderId;
            // to ensure "ticker" is required (not null)
            if (ticker == null)
            {
                throw new ArgumentNullException("ticker is a required property for Order and cannot be null");
            }
            this.Ticker = ticker;
            this.Side = side;
            this.Action = action;
            this.Type = type;
            this.Status = status;
            this.YesPrice = yesPrice;
            this.NoPrice = noPrice;
            // to ensure "yesPriceDollars" is required (not null)
            if (yesPriceDollars == null)
            {
                throw new ArgumentNullException("yesPriceDollars is a required property for Order and cannot be null");
            }
            this.YesPriceDollars = yesPriceDollars;
            // to ensure "noPriceDollars" is required (not null)
            if (noPriceDollars == null)
            {
                throw new ArgumentNullException("noPriceDollars is a required property for Order and cannot be null");
            }
            this.NoPriceDollars = noPriceDollars;
            this.FillCount = fillCount;
            this.RemainingCount = remainingCount;
            this.InitialCount = initialCount;
            this.TakerFees = takerFees;
            this.MakerFees = makerFees;
            this.TakerFillCost = takerFillCost;
            this.MakerFillCost = makerFillCost;
            // to ensure "takerFillCostDollars" is required (not null)
            if (takerFillCostDollars == null)
            {
                throw new ArgumentNullException("takerFillCostDollars is a required property for Order and cannot be null");
            }
            this.TakerFillCostDollars = takerFillCostDollars;
            // to ensure "makerFillCostDollars" is required (not null)
            if (makerFillCostDollars == null)
            {
                throw new ArgumentNullException("makerFillCostDollars is a required property for Order and cannot be null");
            }
            this.MakerFillCostDollars = makerFillCostDollars;
            this.QueuePosition = queuePosition;
            this.TakerFeesDollars = takerFeesDollars;
            this.MakerFeesDollars = makerFeesDollars;
            this.ExpirationTime = expirationTime;
            this.CreatedTime = createdTime;
            this.LastUpdateTime = lastUpdateTime;
            this.SelfTradePreventionType = selfTradePreventionType;
            this.OrderGroupId = orderGroupId;
            this.CancelOrderOnPause = cancelOrderOnPause;
        }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [DataMember(Name = "order_id", IsRequired = true, EmitDefaultValue = true)]
        public string OrderId { get; set; }

        /// <summary>
        /// Unique identifier for users
        /// </summary>
        /// <value>Unique identifier for users</value>
        [DataMember(Name = "user_id", IsRequired = true, EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets ClientOrderId
        /// </summary>
        [DataMember(Name = "client_order_id", IsRequired = true, EmitDefaultValue = true)]
        public string ClientOrderId { get; set; }

        /// <summary>
        /// Gets or Sets Ticker
        /// </summary>
        [DataMember(Name = "ticker", IsRequired = true, EmitDefaultValue = true)]
        public string Ticker { get; set; }

        /// <summary>
        /// Gets or Sets YesPrice
        /// </summary>
        [DataMember(Name = "yes_price", IsRequired = true, EmitDefaultValue = true)]
        public int YesPrice { get; set; }

        /// <summary>
        /// Gets or Sets NoPrice
        /// </summary>
        [DataMember(Name = "no_price", IsRequired = true, EmitDefaultValue = true)]
        public int NoPrice { get; set; }

        /// <summary>
        /// The yes price for this order in fixed-point dollars
        /// </summary>
        /// <value>The yes price for this order in fixed-point dollars</value>
        /*
        <example>0.5000</example>
        */
        [DataMember(Name = "yes_price_dollars", IsRequired = true, EmitDefaultValue = true)]
        public string YesPriceDollars { get; set; }

        /// <summary>
        /// The no price for this order in fixed-point dollars
        /// </summary>
        /// <value>The no price for this order in fixed-point dollars</value>
        /*
        <example>0.5000</example>
        */
        [DataMember(Name = "no_price_dollars", IsRequired = true, EmitDefaultValue = true)]
        public string NoPriceDollars { get; set; }

        /// <summary>
        /// The number of contracts that have been filled
        /// </summary>
        /// <value>The number of contracts that have been filled</value>
        [DataMember(Name = "fill_count", IsRequired = true, EmitDefaultValue = true)]
        public int FillCount { get; set; }

        /// <summary>
        /// Gets or Sets RemainingCount
        /// </summary>
        [DataMember(Name = "remaining_count", IsRequired = true, EmitDefaultValue = true)]
        public int RemainingCount { get; set; }

        /// <summary>
        /// The initial size of the order (contract units)
        /// </summary>
        /// <value>The initial size of the order (contract units)</value>
        [DataMember(Name = "initial_count", IsRequired = true, EmitDefaultValue = true)]
        public int InitialCount { get; set; }

        /// <summary>
        /// Fees paid on filled taker contracts, in cents
        /// </summary>
        /// <value>Fees paid on filled taker contracts, in cents</value>
        [DataMember(Name = "taker_fees", IsRequired = true, EmitDefaultValue = true)]
        public int TakerFees { get; set; }

        /// <summary>
        /// Fees paid on filled maker contracts, in cents
        /// </summary>
        /// <value>Fees paid on filled maker contracts, in cents</value>
        [DataMember(Name = "maker_fees", IsRequired = true, EmitDefaultValue = true)]
        public int MakerFees { get; set; }

        /// <summary>
        /// The cost of filled taker orders in cents
        /// </summary>
        /// <value>The cost of filled taker orders in cents</value>
        [DataMember(Name = "taker_fill_cost", IsRequired = true, EmitDefaultValue = true)]
        public int TakerFillCost { get; set; }

        /// <summary>
        /// The cost of filled maker orders in cents
        /// </summary>
        /// <value>The cost of filled maker orders in cents</value>
        [DataMember(Name = "maker_fill_cost", IsRequired = true, EmitDefaultValue = true)]
        public int MakerFillCost { get; set; }

        /// <summary>
        /// The cost of filled taker orders in dollars
        /// </summary>
        /// <value>The cost of filled taker orders in dollars</value>
        [DataMember(Name = "taker_fill_cost_dollars", IsRequired = true, EmitDefaultValue = true)]
        public string TakerFillCostDollars { get; set; }

        /// <summary>
        /// The cost of filled maker orders in dollars
        /// </summary>
        /// <value>The cost of filled maker orders in dollars</value>
        [DataMember(Name = "maker_fill_cost_dollars", IsRequired = true, EmitDefaultValue = true)]
        public string MakerFillCostDollars { get; set; }

        /// <summary>
        /// **DEPRECATED**: This field is deprecated and will always return 0. Please use the GET /portfolio/orders/{order_id}/queue_position endpoint instead
        /// </summary>
        /// <value>**DEPRECATED**: This field is deprecated and will always return 0. Please use the GET /portfolio/orders/{order_id}/queue_position endpoint instead</value>
        [DataMember(Name = "queue_position", IsRequired = true, EmitDefaultValue = true)]
        public int QueuePosition { get; set; }

        /// <summary>
        /// Fees paid on filled taker contracts, in dollars
        /// </summary>
        /// <value>Fees paid on filled taker contracts, in dollars</value>
        [DataMember(Name = "taker_fees_dollars", EmitDefaultValue = true)]
        public string TakerFeesDollars { get; set; }

        /// <summary>
        /// Fees paid on filled maker contracts, in dollars
        /// </summary>
        /// <value>Fees paid on filled maker contracts, in dollars</value>
        [DataMember(Name = "maker_fees_dollars", EmitDefaultValue = true)]
        public string MakerFeesDollars { get; set; }

        /// <summary>
        /// Gets or Sets ExpirationTime
        /// </summary>
        [DataMember(Name = "expiration_time", EmitDefaultValue = true)]
        public DateTime? ExpirationTime { get; set; }

        /// <summary>
        /// Gets or Sets CreatedTime
        /// </summary>
        [DataMember(Name = "created_time", EmitDefaultValue = true)]
        public DateTime? CreatedTime { get; set; }

        /// <summary>
        /// The last update to an order (modify, cancel, fill)
        /// </summary>
        /// <value>The last update to an order (modify, cancel, fill)</value>
        [DataMember(Name = "last_update_time", EmitDefaultValue = true)]
        public DateTime? LastUpdateTime { get; set; }

        /// <summary>
        /// The order group this order is part of
        /// </summary>
        /// <value>The order group this order is part of</value>
        [DataMember(Name = "order_group_id", EmitDefaultValue = true)]
        public string OrderGroupId { get; set; }

        /// <summary>
        /// If this flag is set to true, the order will be canceled if the order is open and trading on the exchange is paused for any reason.
        /// </summary>
        /// <value>If this flag is set to true, the order will be canceled if the order is open and trading on the exchange is paused for any reason.</value>
        [DataMember(Name = "cancel_order_on_pause", EmitDefaultValue = true)]
        public bool CancelOrderOnPause { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Order {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  ClientOrderId: ").Append(ClientOrderId).Append("\n");
            sb.Append("  Ticker: ").Append(Ticker).Append("\n");
            sb.Append("  Side: ").Append(Side).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  YesPrice: ").Append(YesPrice).Append("\n");
            sb.Append("  NoPrice: ").Append(NoPrice).Append("\n");
            sb.Append("  YesPriceDollars: ").Append(YesPriceDollars).Append("\n");
            sb.Append("  NoPriceDollars: ").Append(NoPriceDollars).Append("\n");
            sb.Append("  FillCount: ").Append(FillCount).Append("\n");
            sb.Append("  RemainingCount: ").Append(RemainingCount).Append("\n");
            sb.Append("  InitialCount: ").Append(InitialCount).Append("\n");
            sb.Append("  TakerFees: ").Append(TakerFees).Append("\n");
            sb.Append("  MakerFees: ").Append(MakerFees).Append("\n");
            sb.Append("  TakerFillCost: ").Append(TakerFillCost).Append("\n");
            sb.Append("  MakerFillCost: ").Append(MakerFillCost).Append("\n");
            sb.Append("  TakerFillCostDollars: ").Append(TakerFillCostDollars).Append("\n");
            sb.Append("  MakerFillCostDollars: ").Append(MakerFillCostDollars).Append("\n");
            sb.Append("  QueuePosition: ").Append(QueuePosition).Append("\n");
            sb.Append("  TakerFeesDollars: ").Append(TakerFeesDollars).Append("\n");
            sb.Append("  MakerFeesDollars: ").Append(MakerFeesDollars).Append("\n");
            sb.Append("  ExpirationTime: ").Append(ExpirationTime).Append("\n");
            sb.Append("  CreatedTime: ").Append(CreatedTime).Append("\n");
            sb.Append("  LastUpdateTime: ").Append(LastUpdateTime).Append("\n");
            sb.Append("  SelfTradePreventionType: ").Append(SelfTradePreventionType).Append("\n");
            sb.Append("  OrderGroupId: ").Append(OrderGroupId).Append("\n");
            sb.Append("  CancelOrderOnPause: ").Append(CancelOrderOnPause).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
