/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// Orderbook
    /// </summary>
    [DataContract(Name = "Orderbook")]
    public partial class Orderbook : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Orderbook" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Orderbook() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Orderbook" /> class.
        /// </summary>
        /// <param name="yes">yes (required).</param>
        /// <param name="no">no (required).</param>
        /// <param name="yesDollars">yesDollars (required).</param>
        /// <param name="noDollars">noDollars (required).</param>
        public Orderbook(List<List<decimal>> yes = default, List<List<decimal>> no = default, List<List<string>> yesDollars = default, List<List<string>> noDollars = default)
        {
            // to ensure "yes" is required (not null)
            if (yes == null)
            {
                throw new ArgumentNullException("yes is a required property for Orderbook and cannot be null");
            }
            this.Yes = yes;
            // to ensure "no" is required (not null)
            if (no == null)
            {
                throw new ArgumentNullException("no is a required property for Orderbook and cannot be null");
            }
            this.No = no;
            // to ensure "yesDollars" is required (not null)
            if (yesDollars == null)
            {
                throw new ArgumentNullException("yesDollars is a required property for Orderbook and cannot be null");
            }
            this.YesDollars = yesDollars;
            // to ensure "noDollars" is required (not null)
            if (noDollars == null)
            {
                throw new ArgumentNullException("noDollars is a required property for Orderbook and cannot be null");
            }
            this.NoDollars = noDollars;
        }

        /// <summary>
        /// Gets or Sets Yes
        /// </summary>
        [DataMember(Name = "yes", IsRequired = true, EmitDefaultValue = true)]
        public List<List<decimal>> Yes { get; set; }

        /// <summary>
        /// Gets or Sets No
        /// </summary>
        [DataMember(Name = "no", IsRequired = true, EmitDefaultValue = true)]
        public List<List<decimal>> No { get; set; }

        /// <summary>
        /// Gets or Sets YesDollars
        /// </summary>
        [DataMember(Name = "yes_dollars", IsRequired = true, EmitDefaultValue = true)]
        public List<List<string>> YesDollars { get; set; }

        /// <summary>
        /// Gets or Sets NoDollars
        /// </summary>
        [DataMember(Name = "no_dollars", IsRequired = true, EmitDefaultValue = true)]
        public List<List<string>> NoDollars { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Orderbook {\n");
            sb.Append("  Yes: ").Append(Yes).Append("\n");
            sb.Append("  No: ").Append(No).Append("\n");
            sb.Append("  YesDollars: ").Append(YesDollars).Append("\n");
            sb.Append("  NoDollars: ").Append(NoDollars).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
