/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// OrderQueuePosition
    /// </summary>
    [DataContract(Name = "OrderQueuePosition")]
    public partial class OrderQueuePosition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderQueuePosition" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OrderQueuePosition() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderQueuePosition" /> class.
        /// </summary>
        /// <param name="orderId">The order ID (required).</param>
        /// <param name="marketTicker">The market ticker (required).</param>
        /// <param name="queuePosition">The position of the order in the queue (required).</param>
        public OrderQueuePosition(string orderId = default, string marketTicker = default, int queuePosition = default)
        {
            // to ensure "orderId" is required (not null)
            if (orderId == null)
            {
                throw new ArgumentNullException("orderId is a required property for OrderQueuePosition and cannot be null");
            }
            this.OrderId = orderId;
            // to ensure "marketTicker" is required (not null)
            if (marketTicker == null)
            {
                throw new ArgumentNullException("marketTicker is a required property for OrderQueuePosition and cannot be null");
            }
            this.MarketTicker = marketTicker;
            this.QueuePosition = queuePosition;
        }

        /// <summary>
        /// The order ID
        /// </summary>
        /// <value>The order ID</value>
        [DataMember(Name = "order_id", IsRequired = true, EmitDefaultValue = true)]
        public string OrderId { get; set; }

        /// <summary>
        /// The market ticker
        /// </summary>
        /// <value>The market ticker</value>
        [DataMember(Name = "market_ticker", IsRequired = true, EmitDefaultValue = true)]
        public string MarketTicker { get; set; }

        /// <summary>
        /// The position of the order in the queue
        /// </summary>
        /// <value>The position of the order in the queue</value>
        [DataMember(Name = "queue_position", IsRequired = true, EmitDefaultValue = true)]
        public int QueuePosition { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderQueuePosition {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  MarketTicker: ").Append(MarketTicker).Append("\n");
            sb.Append("  QueuePosition: ").Append(QueuePosition).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
