/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// OrderGroup
    /// </summary>
    [DataContract(Name = "OrderGroup")]
    public partial class OrderGroup : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderGroup" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OrderGroup() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderGroup" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the order group (required).</param>
        /// <param name="isAutoCancelEnabled">Whether auto-cancel is enabled for this order group (required).</param>
        public OrderGroup(string id = default, bool isAutoCancelEnabled = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for OrderGroup and cannot be null");
            }
            this.Id = id;
            this.IsAutoCancelEnabled = isAutoCancelEnabled;
        }

        /// <summary>
        /// Unique identifier for the order group
        /// </summary>
        /// <value>Unique identifier for the order group</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Whether auto-cancel is enabled for this order group
        /// </summary>
        /// <value>Whether auto-cancel is enabled for this order group</value>
        [DataMember(Name = "is_auto_cancel_enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool IsAutoCancelEnabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderGroup {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IsAutoCancelEnabled: ").Append(IsAutoCancelEnabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
