/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// PercentilePoint
    /// </summary>
    [DataContract(Name = "PercentilePoint")]
    public partial class PercentilePoint : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PercentilePoint" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PercentilePoint() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PercentilePoint" /> class.
        /// </summary>
        /// <param name="percentile">The percentile value (0-10000). (required).</param>
        /// <param name="rawNumericalForecast">The raw numerical forecast value. (required).</param>
        /// <param name="numericalForecast">The processed numerical forecast value. (required).</param>
        /// <param name="formattedForecast">The human-readable formatted forecast value. (required).</param>
        public PercentilePoint(int percentile = default, decimal rawNumericalForecast = default, decimal numericalForecast = default, string formattedForecast = default)
        {
            this.Percentile = percentile;
            this.RawNumericalForecast = rawNumericalForecast;
            this.NumericalForecast = numericalForecast;
            // to ensure "formattedForecast" is required (not null)
            if (formattedForecast == null)
            {
                throw new ArgumentNullException("formattedForecast is a required property for PercentilePoint and cannot be null");
            }
            this.FormattedForecast = formattedForecast;
        }

        /// <summary>
        /// The percentile value (0-10000).
        /// </summary>
        /// <value>The percentile value (0-10000).</value>
        [DataMember(Name = "percentile", IsRequired = true, EmitDefaultValue = true)]
        public int Percentile { get; set; }

        /// <summary>
        /// The raw numerical forecast value.
        /// </summary>
        /// <value>The raw numerical forecast value.</value>
        [DataMember(Name = "raw_numerical_forecast", IsRequired = true, EmitDefaultValue = true)]
        public decimal RawNumericalForecast { get; set; }

        /// <summary>
        /// The processed numerical forecast value.
        /// </summary>
        /// <value>The processed numerical forecast value.</value>
        [DataMember(Name = "numerical_forecast", IsRequired = true, EmitDefaultValue = true)]
        public decimal NumericalForecast { get; set; }

        /// <summary>
        /// The human-readable formatted forecast value.
        /// </summary>
        /// <value>The human-readable formatted forecast value.</value>
        [DataMember(Name = "formatted_forecast", IsRequired = true, EmitDefaultValue = true)]
        public string FormattedForecast { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PercentilePoint {\n");
            sb.Append("  Percentile: ").Append(Percentile).Append("\n");
            sb.Append("  RawNumericalForecast: ").Append(RawNumericalForecast).Append("\n");
            sb.Append("  NumericalForecast: ").Append(NumericalForecast).Append("\n");
            sb.Append("  FormattedForecast: ").Append(FormattedForecast).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
