/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// PriceDistribution
    /// </summary>
    [DataContract(Name = "PriceDistribution")]
    public partial class PriceDistribution : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PriceDistribution" /> class.
        /// </summary>
        /// <param name="open">First traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period..</param>
        /// <param name="openDollars">First traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period..</param>
        /// <param name="low">Lowest traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period..</param>
        /// <param name="lowDollars">Lowest traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period..</param>
        /// <param name="high">Highest traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period..</param>
        /// <param name="highDollars">Highest traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period..</param>
        /// <param name="close">Last traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period..</param>
        /// <param name="closeDollars">Last traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period..</param>
        /// <param name="mean">Mean traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period..</param>
        /// <param name="meanDollars">Mean traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period..</param>
        /// <param name="previous">Last traded YES contract price on the market before the candlestick period (in cents). May be null if there were no trades before the period..</param>
        /// <param name="previousDollars">Last traded YES contract price on the market before the candlestick period (in dollars). May be null if there were no trades before the period..</param>
        /// <param name="min">Minimum close price of any market during the candlestick period (in cents)..</param>
        /// <param name="minDollars">Minimum close price of any market during the candlestick period (in dollars)..</param>
        /// <param name="max">Maximum close price of any market during the candlestick period (in cents)..</param>
        /// <param name="maxDollars">Maximum close price of any market during the candlestick period (in dollars)..</param>
        public PriceDistribution(int? open = default, string openDollars = default, int? low = default, string lowDollars = default, int? high = default, string highDollars = default, int? close = default, string closeDollars = default, int? mean = default, string meanDollars = default, int? previous = default, string previousDollars = default, int? min = default, string minDollars = default, int? max = default, string maxDollars = default)
        {
            this.Open = open;
            this.OpenDollars = openDollars;
            this.Low = low;
            this.LowDollars = lowDollars;
            this.High = high;
            this.HighDollars = highDollars;
            this.Close = close;
            this.CloseDollars = closeDollars;
            this.Mean = mean;
            this.MeanDollars = meanDollars;
            this.Previous = previous;
            this.PreviousDollars = previousDollars;
            this.Min = min;
            this.MinDollars = minDollars;
            this.Max = max;
            this.MaxDollars = maxDollars;
        }

        /// <summary>
        /// First traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period.
        /// </summary>
        /// <value>First traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period.</value>
        [DataMember(Name = "open", EmitDefaultValue = true)]
        public int? Open { get; set; }

        /// <summary>
        /// First traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period.
        /// </summary>
        /// <value>First traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period.</value>
        [DataMember(Name = "open_dollars", EmitDefaultValue = true)]
        public string OpenDollars { get; set; }

        /// <summary>
        /// Lowest traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period.
        /// </summary>
        /// <value>Lowest traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period.</value>
        [DataMember(Name = "low", EmitDefaultValue = true)]
        public int? Low { get; set; }

        /// <summary>
        /// Lowest traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period.
        /// </summary>
        /// <value>Lowest traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period.</value>
        [DataMember(Name = "low_dollars", EmitDefaultValue = true)]
        public string LowDollars { get; set; }

        /// <summary>
        /// Highest traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period.
        /// </summary>
        /// <value>Highest traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period.</value>
        [DataMember(Name = "high", EmitDefaultValue = true)]
        public int? High { get; set; }

        /// <summary>
        /// Highest traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period.
        /// </summary>
        /// <value>Highest traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period.</value>
        [DataMember(Name = "high_dollars", EmitDefaultValue = true)]
        public string HighDollars { get; set; }

        /// <summary>
        /// Last traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period.
        /// </summary>
        /// <value>Last traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period.</value>
        [DataMember(Name = "close", EmitDefaultValue = true)]
        public int? Close { get; set; }

        /// <summary>
        /// Last traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period.
        /// </summary>
        /// <value>Last traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period.</value>
        [DataMember(Name = "close_dollars", EmitDefaultValue = true)]
        public string CloseDollars { get; set; }

        /// <summary>
        /// Mean traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period.
        /// </summary>
        /// <value>Mean traded YES contract price on the market during the candlestick period (in cents). May be null if there was no trade during the period.</value>
        [DataMember(Name = "mean", EmitDefaultValue = true)]
        public int? Mean { get; set; }

        /// <summary>
        /// Mean traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period.
        /// </summary>
        /// <value>Mean traded YES contract price on the market during the candlestick period (in dollars). May be null if there was no trade during the period.</value>
        [DataMember(Name = "mean_dollars", EmitDefaultValue = true)]
        public string MeanDollars { get; set; }

        /// <summary>
        /// Last traded YES contract price on the market before the candlestick period (in cents). May be null if there were no trades before the period.
        /// </summary>
        /// <value>Last traded YES contract price on the market before the candlestick period (in cents). May be null if there were no trades before the period.</value>
        [DataMember(Name = "previous", EmitDefaultValue = true)]
        public int? Previous { get; set; }

        /// <summary>
        /// Last traded YES contract price on the market before the candlestick period (in dollars). May be null if there were no trades before the period.
        /// </summary>
        /// <value>Last traded YES contract price on the market before the candlestick period (in dollars). May be null if there were no trades before the period.</value>
        [DataMember(Name = "previous_dollars", EmitDefaultValue = true)]
        public string PreviousDollars { get; set; }

        /// <summary>
        /// Minimum close price of any market during the candlestick period (in cents).
        /// </summary>
        /// <value>Minimum close price of any market during the candlestick period (in cents).</value>
        [DataMember(Name = "min", EmitDefaultValue = true)]
        public int? Min { get; set; }

        /// <summary>
        /// Minimum close price of any market during the candlestick period (in dollars).
        /// </summary>
        /// <value>Minimum close price of any market during the candlestick period (in dollars).</value>
        [DataMember(Name = "min_dollars", EmitDefaultValue = true)]
        public string MinDollars { get; set; }

        /// <summary>
        /// Maximum close price of any market during the candlestick period (in cents).
        /// </summary>
        /// <value>Maximum close price of any market during the candlestick period (in cents).</value>
        [DataMember(Name = "max", EmitDefaultValue = true)]
        public int? Max { get; set; }

        /// <summary>
        /// Maximum close price of any market during the candlestick period (in dollars).
        /// </summary>
        /// <value>Maximum close price of any market during the candlestick period (in dollars).</value>
        [DataMember(Name = "max_dollars", EmitDefaultValue = true)]
        public string MaxDollars { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PriceDistribution {\n");
            sb.Append("  Open: ").Append(Open).Append("\n");
            sb.Append("  OpenDollars: ").Append(OpenDollars).Append("\n");
            sb.Append("  Low: ").Append(Low).Append("\n");
            sb.Append("  LowDollars: ").Append(LowDollars).Append("\n");
            sb.Append("  High: ").Append(High).Append("\n");
            sb.Append("  HighDollars: ").Append(HighDollars).Append("\n");
            sb.Append("  Close: ").Append(Close).Append("\n");
            sb.Append("  CloseDollars: ").Append(CloseDollars).Append("\n");
            sb.Append("  Mean: ").Append(Mean).Append("\n");
            sb.Append("  MeanDollars: ").Append(MeanDollars).Append("\n");
            sb.Append("  Previous: ").Append(Previous).Append("\n");
            sb.Append("  PreviousDollars: ").Append(PreviousDollars).Append("\n");
            sb.Append("  Min: ").Append(Min).Append("\n");
            sb.Append("  MinDollars: ").Append(MinDollars).Append("\n");
            sb.Append("  Max: ").Append(Max).Append("\n");
            sb.Append("  MaxDollars: ").Append(MaxDollars).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
