/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// Quote
    /// </summary>
    [DataContract(Name = "Quote")]
    public partial class Quote : IValidatableObject
    {
        /// <summary>
        /// Current status of the quote
        /// </summary>
        /// <value>Current status of the quote</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Open for value: open
            /// </summary>
            [EnumMember(Value = "open")]
            Open = 1,

            /// <summary>
            /// Enum Accepted for value: accepted
            /// </summary>
            [EnumMember(Value = "accepted")]
            Accepted = 2,

            /// <summary>
            /// Enum Confirmed for value: confirmed
            /// </summary>
            [EnumMember(Value = "confirmed")]
            Confirmed = 3,

            /// <summary>
            /// Enum Executed for value: executed
            /// </summary>
            [EnumMember(Value = "executed")]
            Executed = 4,

            /// <summary>
            /// Enum Cancelled for value: cancelled
            /// </summary>
            [EnumMember(Value = "cancelled")]
            Cancelled = 5
        }


        /// <summary>
        /// Current status of the quote
        /// </summary>
        /// <value>Current status of the quote</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// The side that was accepted (yes or no)
        /// </summary>
        /// <value>The side that was accepted (yes or no)</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AcceptedSideEnum
        {
            /// <summary>
            /// Enum Yes for value: yes
            /// </summary>
            [EnumMember(Value = "yes")]
            Yes = 1,

            /// <summary>
            /// Enum No for value: no
            /// </summary>
            [EnumMember(Value = "no")]
            No = 2
        }


        /// <summary>
        /// The side that was accepted (yes or no)
        /// </summary>
        /// <value>The side that was accepted (yes or no)</value>
        [DataMember(Name = "accepted_side", EmitDefaultValue = false)]
        public AcceptedSideEnum? AcceptedSide { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Quote" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Quote() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Quote" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the quote (required).</param>
        /// <param name="rfqId">ID of the RFQ this quote is responding to (required).</param>
        /// <param name="creatorId">Public communications ID of the quote creator (required).</param>
        /// <param name="rfqCreatorId">Public communications ID of the RFQ creator (required).</param>
        /// <param name="marketTicker">The ticker of the market this quote is for (required).</param>
        /// <param name="contracts">Number of contracts in the quote (required).</param>
        /// <param name="yesBid">Bid price for YES contracts, in cents (required).</param>
        /// <param name="noBid">Bid price for NO contracts, in cents (required).</param>
        /// <param name="createdTs">Timestamp when the quote was created (required).</param>
        /// <param name="updatedTs">Timestamp when the quote was last updated (required).</param>
        /// <param name="status">Current status of the quote (required).</param>
        /// <param name="acceptedSide">The side that was accepted (yes or no).</param>
        /// <param name="acceptedTs">Timestamp when the quote was accepted.</param>
        /// <param name="confirmedTs">Timestamp when the quote was confirmed.</param>
        /// <param name="executedTs">Timestamp when the quote was executed.</param>
        /// <param name="cancelledTs">Timestamp when the quote was cancelled.</param>
        /// <param name="restRemainder">Whether to rest the remainder of the quote after execution.</param>
        /// <param name="cancellationReason">Reason for quote cancellation if cancelled.</param>
        /// <param name="creatorUserId">User ID of the quote creator (private field).</param>
        /// <param name="rfqCreatorUserId">User ID of the RFQ creator (private field).</param>
        /// <param name="rfqTargetCostCentiCents">Total value requested in the RFQ in centi-cents.</param>
        /// <param name="rfqCreatorOrderId">Order ID for the RFQ creator (private field).</param>
        /// <param name="creatorOrderId">Order ID for the quote creator (private field).</param>
        public Quote(string id = default, string rfqId = default, string creatorId = default, string rfqCreatorId = default, string marketTicker = default, int contracts = default, int yesBid = default, int noBid = default, DateTime createdTs = default, DateTime updatedTs = default, StatusEnum status = default, AcceptedSideEnum? acceptedSide = default, DateTime acceptedTs = default, DateTime confirmedTs = default, DateTime executedTs = default, DateTime cancelledTs = default, bool restRemainder = default, string cancellationReason = default, string creatorUserId = default, string rfqCreatorUserId = default, long rfqTargetCostCentiCents = default, string rfqCreatorOrderId = default, string creatorOrderId = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Quote and cannot be null");
            }
            this.Id = id;
            // to ensure "rfqId" is required (not null)
            if (rfqId == null)
            {
                throw new ArgumentNullException("rfqId is a required property for Quote and cannot be null");
            }
            this.RfqId = rfqId;
            // to ensure "creatorId" is required (not null)
            if (creatorId == null)
            {
                throw new ArgumentNullException("creatorId is a required property for Quote and cannot be null");
            }
            this.CreatorId = creatorId;
            // to ensure "rfqCreatorId" is required (not null)
            if (rfqCreatorId == null)
            {
                throw new ArgumentNullException("rfqCreatorId is a required property for Quote and cannot be null");
            }
            this.RfqCreatorId = rfqCreatorId;
            // to ensure "marketTicker" is required (not null)
            if (marketTicker == null)
            {
                throw new ArgumentNullException("marketTicker is a required property for Quote and cannot be null");
            }
            this.MarketTicker = marketTicker;
            this.Contracts = contracts;
            this.YesBid = yesBid;
            this.NoBid = noBid;
            this.CreatedTs = createdTs;
            this.UpdatedTs = updatedTs;
            this.Status = status;
            this.AcceptedSide = acceptedSide;
            this.AcceptedTs = acceptedTs;
            this.ConfirmedTs = confirmedTs;
            this.ExecutedTs = executedTs;
            this.CancelledTs = cancelledTs;
            this.RestRemainder = restRemainder;
            this.CancellationReason = cancellationReason;
            this.CreatorUserId = creatorUserId;
            this.RfqCreatorUserId = rfqCreatorUserId;
            this.RfqTargetCostCentiCents = rfqTargetCostCentiCents;
            this.RfqCreatorOrderId = rfqCreatorOrderId;
            this.CreatorOrderId = creatorOrderId;
        }

        /// <summary>
        /// Unique identifier for the quote
        /// </summary>
        /// <value>Unique identifier for the quote</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// ID of the RFQ this quote is responding to
        /// </summary>
        /// <value>ID of the RFQ this quote is responding to</value>
        [DataMember(Name = "rfq_id", IsRequired = true, EmitDefaultValue = true)]
        public string RfqId { get; set; }

        /// <summary>
        /// Public communications ID of the quote creator
        /// </summary>
        /// <value>Public communications ID of the quote creator</value>
        [DataMember(Name = "creator_id", IsRequired = true, EmitDefaultValue = true)]
        public string CreatorId { get; set; }

        /// <summary>
        /// Public communications ID of the RFQ creator
        /// </summary>
        /// <value>Public communications ID of the RFQ creator</value>
        [DataMember(Name = "rfq_creator_id", IsRequired = true, EmitDefaultValue = true)]
        public string RfqCreatorId { get; set; }

        /// <summary>
        /// The ticker of the market this quote is for
        /// </summary>
        /// <value>The ticker of the market this quote is for</value>
        [DataMember(Name = "market_ticker", IsRequired = true, EmitDefaultValue = true)]
        public string MarketTicker { get; set; }

        /// <summary>
        /// Number of contracts in the quote
        /// </summary>
        /// <value>Number of contracts in the quote</value>
        [DataMember(Name = "contracts", IsRequired = true, EmitDefaultValue = true)]
        public int Contracts { get; set; }

        /// <summary>
        /// Bid price for YES contracts, in cents
        /// </summary>
        /// <value>Bid price for YES contracts, in cents</value>
        [DataMember(Name = "yes_bid", IsRequired = true, EmitDefaultValue = true)]
        public int YesBid { get; set; }

        /// <summary>
        /// Bid price for NO contracts, in cents
        /// </summary>
        /// <value>Bid price for NO contracts, in cents</value>
        [DataMember(Name = "no_bid", IsRequired = true, EmitDefaultValue = true)]
        public int NoBid { get; set; }

        /// <summary>
        /// Timestamp when the quote was created
        /// </summary>
        /// <value>Timestamp when the quote was created</value>
        [DataMember(Name = "created_ts", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedTs { get; set; }

        /// <summary>
        /// Timestamp when the quote was last updated
        /// </summary>
        /// <value>Timestamp when the quote was last updated</value>
        [DataMember(Name = "updated_ts", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedTs { get; set; }

        /// <summary>
        /// Timestamp when the quote was accepted
        /// </summary>
        /// <value>Timestamp when the quote was accepted</value>
        [DataMember(Name = "accepted_ts", EmitDefaultValue = false)]
        public DateTime AcceptedTs { get; set; }

        /// <summary>
        /// Timestamp when the quote was confirmed
        /// </summary>
        /// <value>Timestamp when the quote was confirmed</value>
        [DataMember(Name = "confirmed_ts", EmitDefaultValue = false)]
        public DateTime ConfirmedTs { get; set; }

        /// <summary>
        /// Timestamp when the quote was executed
        /// </summary>
        /// <value>Timestamp when the quote was executed</value>
        [DataMember(Name = "executed_ts", EmitDefaultValue = false)]
        public DateTime ExecutedTs { get; set; }

        /// <summary>
        /// Timestamp when the quote was cancelled
        /// </summary>
        /// <value>Timestamp when the quote was cancelled</value>
        [DataMember(Name = "cancelled_ts", EmitDefaultValue = false)]
        public DateTime CancelledTs { get; set; }

        /// <summary>
        /// Whether to rest the remainder of the quote after execution
        /// </summary>
        /// <value>Whether to rest the remainder of the quote after execution</value>
        [DataMember(Name = "rest_remainder", EmitDefaultValue = true)]
        public bool RestRemainder { get; set; }

        /// <summary>
        /// Reason for quote cancellation if cancelled
        /// </summary>
        /// <value>Reason for quote cancellation if cancelled</value>
        [DataMember(Name = "cancellation_reason", EmitDefaultValue = false)]
        public string CancellationReason { get; set; }

        /// <summary>
        /// User ID of the quote creator (private field)
        /// </summary>
        /// <value>User ID of the quote creator (private field)</value>
        [DataMember(Name = "creator_user_id", EmitDefaultValue = false)]
        public string CreatorUserId { get; set; }

        /// <summary>
        /// User ID of the RFQ creator (private field)
        /// </summary>
        /// <value>User ID of the RFQ creator (private field)</value>
        [DataMember(Name = "rfq_creator_user_id", EmitDefaultValue = false)]
        public string RfqCreatorUserId { get; set; }

        /// <summary>
        /// Total value requested in the RFQ in centi-cents
        /// </summary>
        /// <value>Total value requested in the RFQ in centi-cents</value>
        [DataMember(Name = "rfq_target_cost_centi_cents", EmitDefaultValue = false)]
        public long RfqTargetCostCentiCents { get; set; }

        /// <summary>
        /// Order ID for the RFQ creator (private field)
        /// </summary>
        /// <value>Order ID for the RFQ creator (private field)</value>
        [DataMember(Name = "rfq_creator_order_id", EmitDefaultValue = false)]
        public string RfqCreatorOrderId { get; set; }

        /// <summary>
        /// Order ID for the quote creator (private field)
        /// </summary>
        /// <value>Order ID for the quote creator (private field)</value>
        [DataMember(Name = "creator_order_id", EmitDefaultValue = false)]
        public string CreatorOrderId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Quote {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  RfqId: ").Append(RfqId).Append("\n");
            sb.Append("  CreatorId: ").Append(CreatorId).Append("\n");
            sb.Append("  RfqCreatorId: ").Append(RfqCreatorId).Append("\n");
            sb.Append("  MarketTicker: ").Append(MarketTicker).Append("\n");
            sb.Append("  Contracts: ").Append(Contracts).Append("\n");
            sb.Append("  YesBid: ").Append(YesBid).Append("\n");
            sb.Append("  NoBid: ").Append(NoBid).Append("\n");
            sb.Append("  CreatedTs: ").Append(CreatedTs).Append("\n");
            sb.Append("  UpdatedTs: ").Append(UpdatedTs).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  AcceptedSide: ").Append(AcceptedSide).Append("\n");
            sb.Append("  AcceptedTs: ").Append(AcceptedTs).Append("\n");
            sb.Append("  ConfirmedTs: ").Append(ConfirmedTs).Append("\n");
            sb.Append("  ExecutedTs: ").Append(ExecutedTs).Append("\n");
            sb.Append("  CancelledTs: ").Append(CancelledTs).Append("\n");
            sb.Append("  RestRemainder: ").Append(RestRemainder).Append("\n");
            sb.Append("  CancellationReason: ").Append(CancellationReason).Append("\n");
            sb.Append("  CreatorUserId: ").Append(CreatorUserId).Append("\n");
            sb.Append("  RfqCreatorUserId: ").Append(RfqCreatorUserId).Append("\n");
            sb.Append("  RfqTargetCostCentiCents: ").Append(RfqTargetCostCentiCents).Append("\n");
            sb.Append("  RfqCreatorOrderId: ").Append(RfqCreatorOrderId).Append("\n");
            sb.Append("  CreatorOrderId: ").Append(CreatorOrderId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
