/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// RFQ
    /// </summary>
    [DataContract(Name = "RFQ")]
    public partial class RFQ : IValidatableObject
    {
        /// <summary>
        /// Current status of the RFQ (open, closed)
        /// </summary>
        /// <value>Current status of the RFQ (open, closed)</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Open for value: open
            /// </summary>
            [EnumMember(Value = "open")]
            Open = 1,

            /// <summary>
            /// Enum Closed for value: closed
            /// </summary>
            [EnumMember(Value = "closed")]
            Closed = 2
        }


        /// <summary>
        /// Current status of the RFQ (open, closed)
        /// </summary>
        /// <value>Current status of the RFQ (open, closed)</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RFQ" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RFQ() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RFQ" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the RFQ (required).</param>
        /// <param name="creatorId">Public communications ID of the RFQ creator (required).</param>
        /// <param name="marketTicker">The ticker of the market this RFQ is for (required).</param>
        /// <param name="contracts">Number of contracts requested in the RFQ (required).</param>
        /// <param name="targetCostCentiCents">Total value of the RFQ in centi-cents.</param>
        /// <param name="status">Current status of the RFQ (open, closed) (required).</param>
        /// <param name="createdTs">Timestamp when the RFQ was created (required).</param>
        /// <param name="mveCollectionTicker">Ticker of the MVE collection this market belongs to.</param>
        /// <param name="mveSelectedLegs">Selected legs for the MVE collection.</param>
        /// <param name="restRemainder">Whether to rest the remainder of the RFQ after execution.</param>
        /// <param name="cancellationReason">Reason for RFQ cancellation if cancelled.</param>
        /// <param name="creatorUserId">User ID of the RFQ creator (private field).</param>
        /// <param name="cancelledTs">Timestamp when the RFQ was cancelled.</param>
        /// <param name="updatedTs">Timestamp when the RFQ was last updated.</param>
        public RFQ(string id = default, string creatorId = default, string marketTicker = default, int contracts = default, long targetCostCentiCents = default, StatusEnum status = default, DateTime createdTs = default, string mveCollectionTicker = default, List<MveSelectedLeg> mveSelectedLegs = default, bool restRemainder = default, string cancellationReason = default, string creatorUserId = default, DateTime cancelledTs = default, DateTime updatedTs = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for RFQ and cannot be null");
            }
            this.Id = id;
            // to ensure "creatorId" is required (not null)
            if (creatorId == null)
            {
                throw new ArgumentNullException("creatorId is a required property for RFQ and cannot be null");
            }
            this.CreatorId = creatorId;
            // to ensure "marketTicker" is required (not null)
            if (marketTicker == null)
            {
                throw new ArgumentNullException("marketTicker is a required property for RFQ and cannot be null");
            }
            this.MarketTicker = marketTicker;
            this.Contracts = contracts;
            this.Status = status;
            this.CreatedTs = createdTs;
            this.TargetCostCentiCents = targetCostCentiCents;
            this.MveCollectionTicker = mveCollectionTicker;
            this.MveSelectedLegs = mveSelectedLegs;
            this.RestRemainder = restRemainder;
            this.CancellationReason = cancellationReason;
            this.CreatorUserId = creatorUserId;
            this.CancelledTs = cancelledTs;
            this.UpdatedTs = updatedTs;
        }

        /// <summary>
        /// Unique identifier for the RFQ
        /// </summary>
        /// <value>Unique identifier for the RFQ</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Public communications ID of the RFQ creator
        /// </summary>
        /// <value>Public communications ID of the RFQ creator</value>
        [DataMember(Name = "creator_id", IsRequired = true, EmitDefaultValue = true)]
        public string CreatorId { get; set; }

        /// <summary>
        /// The ticker of the market this RFQ is for
        /// </summary>
        /// <value>The ticker of the market this RFQ is for</value>
        [DataMember(Name = "market_ticker", IsRequired = true, EmitDefaultValue = true)]
        public string MarketTicker { get; set; }

        /// <summary>
        /// Number of contracts requested in the RFQ
        /// </summary>
        /// <value>Number of contracts requested in the RFQ</value>
        [DataMember(Name = "contracts", IsRequired = true, EmitDefaultValue = true)]
        public int Contracts { get; set; }

        /// <summary>
        /// Total value of the RFQ in centi-cents
        /// </summary>
        /// <value>Total value of the RFQ in centi-cents</value>
        [DataMember(Name = "target_cost_centi_cents", EmitDefaultValue = false)]
        public long TargetCostCentiCents { get; set; }

        /// <summary>
        /// Timestamp when the RFQ was created
        /// </summary>
        /// <value>Timestamp when the RFQ was created</value>
        [DataMember(Name = "created_ts", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedTs { get; set; }

        /// <summary>
        /// Ticker of the MVE collection this market belongs to
        /// </summary>
        /// <value>Ticker of the MVE collection this market belongs to</value>
        [DataMember(Name = "mve_collection_ticker", EmitDefaultValue = false)]
        public string MveCollectionTicker { get; set; }

        /// <summary>
        /// Selected legs for the MVE collection
        /// </summary>
        /// <value>Selected legs for the MVE collection</value>
        [DataMember(Name = "mve_selected_legs", EmitDefaultValue = false)]
        public List<MveSelectedLeg> MveSelectedLegs { get; set; }

        /// <summary>
        /// Whether to rest the remainder of the RFQ after execution
        /// </summary>
        /// <value>Whether to rest the remainder of the RFQ after execution</value>
        [DataMember(Name = "rest_remainder", EmitDefaultValue = true)]
        public bool RestRemainder { get; set; }

        /// <summary>
        /// Reason for RFQ cancellation if cancelled
        /// </summary>
        /// <value>Reason for RFQ cancellation if cancelled</value>
        [DataMember(Name = "cancellation_reason", EmitDefaultValue = false)]
        public string CancellationReason { get; set; }

        /// <summary>
        /// User ID of the RFQ creator (private field)
        /// </summary>
        /// <value>User ID of the RFQ creator (private field)</value>
        [DataMember(Name = "creator_user_id", EmitDefaultValue = false)]
        public string CreatorUserId { get; set; }

        /// <summary>
        /// Timestamp when the RFQ was cancelled
        /// </summary>
        /// <value>Timestamp when the RFQ was cancelled</value>
        [DataMember(Name = "cancelled_ts", EmitDefaultValue = false)]
        public DateTime CancelledTs { get; set; }

        /// <summary>
        /// Timestamp when the RFQ was last updated
        /// </summary>
        /// <value>Timestamp when the RFQ was last updated</value>
        [DataMember(Name = "updated_ts", EmitDefaultValue = false)]
        public DateTime UpdatedTs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RFQ {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatorId: ").Append(CreatorId).Append("\n");
            sb.Append("  MarketTicker: ").Append(MarketTicker).Append("\n");
            sb.Append("  Contracts: ").Append(Contracts).Append("\n");
            sb.Append("  TargetCostCentiCents: ").Append(TargetCostCentiCents).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedTs: ").Append(CreatedTs).Append("\n");
            sb.Append("  MveCollectionTicker: ").Append(MveCollectionTicker).Append("\n");
            sb.Append("  MveSelectedLegs: ").Append(MveSelectedLegs).Append("\n");
            sb.Append("  RestRemainder: ").Append(RestRemainder).Append("\n");
            sb.Append("  CancellationReason: ").Append(CancellationReason).Append("\n");
            sb.Append("  CreatorUserId: ").Append(CreatorUserId).Append("\n");
            sb.Append("  CancelledTs: ").Append(CancelledTs).Append("\n");
            sb.Append("  UpdatedTs: ").Append(UpdatedTs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
