/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// Schedule
    /// </summary>
    [DataContract(Name = "Schedule")]
    public partial class Schedule : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Schedule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Schedule() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Schedule" /> class.
        /// </summary>
        /// <param name="standardHours">The standard operating hours of the exchange. All times are expressed in ET. Outside of these times trading will be unavailable. (required).</param>
        /// <param name="maintenanceWindows">Scheduled maintenance windows, during which the exchange may be unavailable. (required).</param>
        public Schedule(List<WeeklySchedule> standardHours = default, List<MaintenanceWindow> maintenanceWindows = default)
        {
            // to ensure "standardHours" is required (not null)
            if (standardHours == null)
            {
                throw new ArgumentNullException("standardHours is a required property for Schedule and cannot be null");
            }
            this.StandardHours = standardHours;
            // to ensure "maintenanceWindows" is required (not null)
            if (maintenanceWindows == null)
            {
                throw new ArgumentNullException("maintenanceWindows is a required property for Schedule and cannot be null");
            }
            this.MaintenanceWindows = maintenanceWindows;
        }

        /// <summary>
        /// The standard operating hours of the exchange. All times are expressed in ET. Outside of these times trading will be unavailable.
        /// </summary>
        /// <value>The standard operating hours of the exchange. All times are expressed in ET. Outside of these times trading will be unavailable.</value>
        [DataMember(Name = "standard_hours", IsRequired = true, EmitDefaultValue = true)]
        public List<WeeklySchedule> StandardHours { get; set; }

        /// <summary>
        /// Scheduled maintenance windows, during which the exchange may be unavailable.
        /// </summary>
        /// <value>Scheduled maintenance windows, during which the exchange may be unavailable.</value>
        [DataMember(Name = "maintenance_windows", IsRequired = true, EmitDefaultValue = true)]
        public List<MaintenanceWindow> MaintenanceWindows { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Schedule {\n");
            sb.Append("  StandardHours: ").Append(StandardHours).Append("\n");
            sb.Append("  MaintenanceWindows: ").Append(MaintenanceWindows).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
