/*
 * Kalshi Trade API Manual Endpoints
 *
 * Manually defined OpenAPI spec for endpoints being migrated to spec-first approach
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kalshi.Api.Client.OpenAPIDateConverter;

namespace Kalshi.Api.Model
{
    /// <summary>
    /// StructuredTarget
    /// </summary>
    [DataContract(Name = "StructuredTarget")]
    public partial class StructuredTarget : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StructuredTarget" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the structured target..</param>
        /// <param name="name">Name of the structured target..</param>
        /// <param name="type">Type of the structured target..</param>
        /// <param name="details">Additional details about the structured target. Contains flexible JSON data specific to the target type..</param>
        /// <param name="sourceId">External source identifier for the structured target, if available (e.g., third-party data provider ID)..</param>
        /// <param name="lastUpdatedTs">Timestamp when this structured target was last updated..</param>
        public StructuredTarget(string id = default, string name = default, string type = default, Object details = default, string sourceId = default, DateTime lastUpdatedTs = default)
        {
            this.Id = id;
            this.Name = name;
            this.Type = type;
            this.Details = details;
            this.SourceId = sourceId;
            this.LastUpdatedTs = lastUpdatedTs;
        }

        /// <summary>
        /// Unique identifier for the structured target.
        /// </summary>
        /// <value>Unique identifier for the structured target.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Name of the structured target.
        /// </summary>
        /// <value>Name of the structured target.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Type of the structured target.
        /// </summary>
        /// <value>Type of the structured target.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Additional details about the structured target. Contains flexible JSON data specific to the target type.
        /// </summary>
        /// <value>Additional details about the structured target. Contains flexible JSON data specific to the target type.</value>
        [DataMember(Name = "details", EmitDefaultValue = false)]
        public Object Details { get; set; }

        /// <summary>
        /// External source identifier for the structured target, if available (e.g., third-party data provider ID).
        /// </summary>
        /// <value>External source identifier for the structured target, if available (e.g., third-party data provider ID).</value>
        [DataMember(Name = "source_id", EmitDefaultValue = false)]
        public string SourceId { get; set; }

        /// <summary>
        /// Timestamp when this structured target was last updated.
        /// </summary>
        /// <value>Timestamp when this structured target was last updated.</value>
        [DataMember(Name = "last_updated_ts", EmitDefaultValue = false)]
        public DateTime LastUpdatedTs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StructuredTarget {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("  SourceId: ").Append(SourceId).Append("\n");
            sb.Append("  LastUpdatedTs: ").Append(LastUpdatedTs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
